"""Topics 41–78: data, integration, reliability, cost, and operations."""
from aws_architect_topic_factory import topic


TOPICS = [
    topic(41, "S3 Object Model、Consistency 與 Security",
          "Object storage提供近乎無限namespace，但bucket、object、prefix與HTTP API不同於檔案系統。",
          "以bucket policy、IAM、Block Public Access與encryption建立邊界，依key設計平行存取。",
          "EFS提供共享POSIX語意；若應用依賴append、locking或directory rename，不應只因容量選S3。",
          "開放public bucket、忽略cross-account ownership，或把一次LIST結果當transaction snapshot。",
          "object storage scales by immutable objects and explicit metadata",
          "資料平台每天寫入十億個事件物件，僅分析角色可讀，外部客戶以限時連結下載。",
          "Amazon S3|S3 Block Public Access|S3 bucket policies"),
    topic(42, "S3 Storage Classes、Lifecycle 與 Archival",
          "同一份資料的存取頻率會隨時間改變，儲存單價之外還有retrieval、minimum duration與request成本。",
          "用access pattern與復原時間選Standard、IA、One Zone-IA、Intelligent-Tiering與Glacier classes。",
          "Intelligent-Tiering降低未知pattern的決策成本，但仍需理解archive tier取回延遲。",
          "把每天讀取的資料轉Glacier，或忽略minimum storage duration與小物件轉換費。",
          "optimize lifecycle using total access cost, not storage price",
          "合規log前30天常查，之後六年幾乎不讀，但法律要求數小時內可取回。",
          "Amazon S3|S3 Lifecycle|S3 Glacier"),
    topic(43, "EBS、EFS 與 FSx 選型",
          "共享方式、protocol、latency與workload相容性決定block/file服務。",
          "單EC2低延遲block用EBS；Linux共享NFS用EFS；Windows/Lustre/NetApp/OpenZFS需求用對應FSx。",
          "EFS elastic吞吐降低容量規劃，FSx可提供特定檔案系統功能與高效能。",
          "跨AZ application使用單AZ EBS當共享盤，或忽略EFS throughput mode。",
          "filesystem semantics are part of the application contract",
          "Windows home directory、HPC scratch與Linux web uploads需要不同共享檔案服務。",
          "Amazon EBS|Amazon EFS|Amazon FSx"),
    topic(44, "Storage Gateway、DataSync、Transfer 與 Snow",
          "資料搬移受網路頻寬、停機窗口、protocol、持續同步與實體運送限制。",
          "DataSync做高效online transfer；Storage Gateway提供hybrid介面；Transfer Family接SFTP；Snow處理離線大量資料。",
          "DMS適合資料庫持續複寫，不應代替一般檔案搬移。",
          "只用理論頻寬估算PB傳輸，忽略小檔metadata、變更率、驗證與cutover。",
          "migration throughput is bytes plus change rate plus verification",
          "資料中心有3PB影像、每日新增20TB，合作夥伴仍用SFTP。",
          "AWS DataSync|AWS Storage Gateway|AWS Transfer Family|AWS Snow Family"),
    topic(45, "RDS Multi-AZ、Read Replica 與 RDS Proxy",
          "關聯式資料庫的HA、read scaling與connection management是三個不同問題。",
          "Multi-AZ提供同步standby/failover；read replica服務讀取與DR；RDS Proxy吸收短生命connection。",
          "Aurora有不同storage與replica架構，不能把所有RDS行為直接套用。",
          "把read replica當零RPO HA，或Lambda直接建立大量DB connections。",
          "separate availability replicas from read-scaling replicas",
          "交易主庫需自動failover，報表流量不能影響寫入，Lambda尖峰達數千併發。",
          "Amazon RDS|RDS Multi-AZ|RDS read replicas|Amazon RDS Proxy"),
    topic(46, "Aurora、Global Database 與 Serverless",
          "雲端關聯式workload需要更快failover、跨Region讀取或依需求調整容量。",
          "Aurora replicas共享distributed storage；Global Database提供跨Region複寫；Serverless依版本與需求彈性配置。",
          "標準RDS可能更便宜且引擎相容性更直接，應依feature與成本選擇。",
          "將跨Region replica當同步零資料遺失，或忽略promotion、DNS與write endpoint切換。",
          "shared storage changes replica economics but not application recovery",
          "全球SaaS主寫在美國，歐洲低延遲讀取，Region事故需在幾分鐘內恢復。",
          "Amazon Aurora|Aurora Global Database|Aurora Serverless"),
    topic(47, "DynamoDB Partition、Capacity、GSI 與 DAX",
          "DynamoDB依partition key分散資料，schema設計必須由access patterns與流量分布開始。",
          "選高基數均勻key，透過composite key/GSI支援查詢，依流量選on-demand或provisioned。",
          "DAX加速eventually consistent reads；Global Tables處理multi-Region active-active。",
          "使用Scan代替query、建立hot key，或誤以為GSI與base table同步transaction更新。",
          "distributed databases expose partition design through performance",
          "遊戲排行榜每秒數十萬寫入，需依玩家與時間查詢並避免單一熱門partition。",
          "Amazon DynamoDB|DynamoDB global secondary indexes|DAX|DynamoDB Global Tables"),
    topic(48, "ElastiCache 與 Caching Patterns",
          "Cache可降低origin負載與延遲，但引入staleness、eviction與stampede。",
          "Cache-aside適合一般讀取；write-through保持較新資料；Redis支援複雜結構，Memcached偏簡單分散cache。",
          "CloudFront處理edge HTTP cache，DAX處理DynamoDB API，不是所有cache都可互換。",
          "TTL同時到期造成thundering herd，或把cache當唯一資料來源。",
          "cache is a disposable projection of authoritative state",
          "產品頁讀多寫少，但促銷更新後必須快速失效，熱門key會同時到期。",
          "Amazon ElastiCache|Amazon CloudFront|Amazon DynamoDB Accelerator"),
    topic(49, "Redshift、Athena、Glue 與 Lake Formation",
          "分析平台要區分warehouse、query-on-object、catalog/ETL與data governance。",
          "穩定高效BI用Redshift；ad hoc S3 SQL用Athena；Glue管理catalog/ETL；Lake Formation治理lake權限。",
          "EMR適合需要Spark/Hadoop控制的處理，QuickSight提供BI visualization。",
          "讓Athena掃描未分區raw JSON導致慢與貴，或同時維護多個不一致catalog。",
          "separate storage, catalog, compute, and governance planes",
          "公司資料都在S3，分析師偶爾查詢，BI dashboard每天高頻聚合。",
          "Amazon Redshift|Amazon Athena|AWS Glue|AWS Lake Formation"),
    topic(50, "Kinesis、MSK 與 Streaming Pipeline",
          "Streaming需要定義ordering、retention、partition、consumer、replay與backpressure。",
          "AWS-native shard stream用Kinesis；Kafka ecosystem/portability用MSK；delivery到S3等用Data Firehose。",
          "SQS適合work queue而非保留可供多consumer replay的ordered log。",
          "以單一partition key形成hot shard，或consumer lag增加時只擴producer。",
          "a stream is a replayable ordered log partitioned by key",
          "IoT事件需多個獨立consumer即時處理並可回放24小時，既有團隊熟悉Kafka。",
          "Amazon Kinesis Data Streams|Amazon MSK|Amazon Data Firehose"),
    topic(51, "OpenSearch、DocumentDB、Neptune 與 Purpose-built DB",
          "搜尋、文件、圖與時序查詢若硬塞關聯資料庫，會產生複雜索引與不穩定效能。",
          "全文搜尋用OpenSearch；MongoDB相容文件用DocumentDB；關係遍歷用Neptune；時序用Timestream。",
          "Purpose-built store改善特定access pattern，但增加同步、備份與技能負擔。",
          "只因資料是JSON就選DocumentDB，或將OpenSearch當唯一system of record。",
          "specialized read models should not silently become authoritative stores",
          "詐欺系統需遍歷帳戶關係、搜尋文字紀錄並保存原始交易。",
          "Amazon OpenSearch Service|Amazon DocumentDB|Amazon Neptune|Amazon Timestream"),

    topic(52, "SQS Standard、FIFO、Visibility 與 DLQ",
          "Producer與consumer速率不同，工作需要buffer、retry與失敗隔離。",
          "Standard queue追求高吞吐並接受至少一次與可能重排；FIFO在message group內提供順序與去重。",
          "Visibility timeout要覆蓋處理時間並可延長；DLQ需設定redrive與告警。",
          "處理成功前刪除message、timeout太短造成並行重複，或DLQ無人處理。",
          "queues decouple time but require idempotent consumers",
          "影像工作耗時1到10分鐘，偶爾失敗，促銷尖峰producer增加百倍。",
          "Amazon SQS|SQS FIFO queues|Dead-letter queues"),
    topic(53, "SNS、EventBridge 與 Publish-Subscribe",
          "一個事件可能需要推送到多個subscriber，並依內容routing到不同targets。",
          "SNS做直接fan-out與mobile/SMS；EventBridge做event bus、filtering、archive與SaaS整合。",
          "SQS常放在subscriber前吸收背壓；EventBridge不取代長期stream replay。",
          "直接同步呼叫所有subscriber，使一個慢服務拖垮producer。",
          "publish facts once, let consumers own their pace",
          "訂單成立後庫存、通知、分析與詐欺服務都要獨立處理。",
          "Amazon SNS|Amazon EventBridge|Amazon SQS"),
    topic(54, "Kinesis Ordering、Partition 與 Consumer Scaling",
          "需要同key順序的高速事件流，容量由shards/partitions與consumer方式決定。",
          "以business key分partition，監控iterator age，按吞吐與hot key拆分。",
          "Enhanced fan-out隔離consumer throughput；Firehose適合delivery而非任意consumer logic。",
          "把所有事件用tenant常數當partition key，單shard成為瓶頸。",
          "ordering scope and partition key are the same design decision",
          "每位使用者事件需有序，不同使用者可平行，三個consumer各自讀取。",
          "Amazon Kinesis Data Streams|Enhanced fan-out|Amazon Data Firehose"),
    topic(55, "Step Functions、Workflow 與 Human Approval",
          "多步驟流程需要state、retry、timeout、branch與補償，不能只靠函式互相呼叫。",
          "Step Functions明確表達state machine；Standard適合durable workflow，Express適合高量短流程。",
          "EventBridge適合事件routing；SQS適合工作buffer；它們可與workflow組合。",
          "Lambda內手寫長時間sleep/polling，或retry非冪等步驟造成重複扣款。",
          "make orchestration state explicit and inspectable",
          "貸款流程需平行查核、人工核准、72小時等待與失敗補償。",
          "AWS Step Functions|Standard Workflows|Express Workflows"),
    topic(56, "Retry、Backoff、Jitter 與 Timeout",
          "分散式呼叫會暫時失敗，但無限制重試會把小故障放大成retry storm。",
          "每次呼叫設timeout，只重試可恢復且冪等操作，使用exponential backoff、jitter與總deadline。",
          "Circuit breaker可在持續故障時快速失敗；queue可把立即重試轉成受控重排程。",
          "每一層各重試三次，五層組合成數百次下游request。",
          "retries consume a shared failure budget",
          "下游偶發429與timeout，client、service mesh與SDK都內建重試。",
          "AWS SDK retry behavior|Amazon API Gateway|AWS Lambda"),
    topic(57, "Idempotency、Deduplication 與 Exactly-once Illusion",
          "Client看不到response時無法判斷server是否已提交，重試可能重複side effect。",
          "以idempotency key保存operation outcome，consumer以business identity去重並讓寫入可重放。",
          "FIFO deduplication有時間與範圍邊界，不能取代業務層idempotency。",
          "用message ID去重卻在重新發布時產生新ID，付款因此重複。",
          "exactly-once effects are built from at-least-once delivery plus idempotency",
          "付款已完成但response丟失，client在timeout後重送相同request。",
          "Amazon DynamoDB|Amazon SQS FIFO|AWS Lambda Powertools"),
    topic(58, "Saga、Transactional Outbox 與 Eventual Consistency",
          "跨服務無法用單一ACID transaction同時更新database與message broker。",
          "本地transaction寫business state與outbox，再發布事件；Saga用補償或協調處理多步流程。",
          "Orchestration集中flow可見性；choreography降低中央耦合但事件關係較難追。",
          "先commit DB再publish時process crash，造成狀態已改但事件永遠遺失。",
          "make state transition and event publication one durable decision",
          "訂單需扣庫存、付款、建立物流，任何一步可能失敗且各服務有自己的database。",
          "AWS Step Functions|Amazon EventBridge|Amazon DynamoDB Streams"),
    topic(59, "Circuit Breaker、Bulkhead 與 Backpressure",
          "慢依賴會佔滿thread、connection與queue，把局部故障傳到整個系統。",
          "Timeout限制等待，circuit breaker阻止無效呼叫，bulkhead隔離資源，bounded queue回傳背壓。",
          "Autoscaling可增加容量但不能修復完全失效依賴或無限arrival rate。",
          "用unbounded queue隱藏過載，直到memory耗盡且所有request都過期。",
          "protect scarce resources before maximizing throughput",
          "推薦服務變慢後，結帳API的thread pool也被占滿，但推薦其實可降級。",
          "Elastic Load Balancing|Amazon SQS|AWS Lambda reserved concurrency"),
    topic(60, "Stateless、Stateful、Sync 與 Async",
          "架構需要明確知道state owner與等待關係，才能安全scale與failover。",
          "可重建compute保持stateless；durable state交給專用store；長工作透過async queue回傳job ID。",
          "同步適合需要立即結果且延遲可控；非同步適合吸收burst與解耦可用性。",
          "把session鎖在單instance，或將需要立即一致結果的交易全部改成eventual async。",
          "state placement determines scaling and failure behavior",
          "報表產生需十分鐘，使用者不應維持HTTP connection等待。",
          "Amazon SQS|AWS Step Functions|Amazon ElastiCache"),

    topic(61, "Multi-AZ、Multi-Region 與 Fault Domains",
          "副本只有放在獨立failure domain，才能抵抗對應範圍的故障。",
          "先用Multi-AZ處理datacenter級故障，再依business continuity需求評估Multi-Region。",
          "Multi-Region提高resilience與latency選項，但帶來資料一致性、部署、成本與操作複雜度。",
          "將所有副本放同一AZ，或宣稱multi-Region卻共享單一identity/DNS/control dependency。",
          "resilience is limited by the largest shared dependency",
          "服務要抵抗AZ故障；只有法規與極低RTO服務需要跨Region運作。",
          "Availability Zones|AWS Regions|Amazon Route 53"),
    topic(62, "Backup、Pilot Light、Warm Standby 與 Active-Active",
          "DR策略由RTO、RPO、成本與操作成熟度決定，不是越昂貴越好。",
          "Backup/restore成本最低；pilot light保留核心；warm standby保留縮小環境；active-active常駐兩地。",
          "Active-passive通常較易維持單一writer語意，active-active需衝突處理。",
          "建立第二Region資源卻沒有資料、IAM、DNS與runbook同步。",
          "recovery architecture must be continuously executable",
          "四套系統分別可接受24小時、4小時、30分鐘與近零停機。",
          "AWS Backup|AWS Elastic Disaster Recovery|Amazon Route 53"),
    topic(63, "RTO/RPO 驅動的 DR 設計",
          "若不將business impact轉成可測量目標，恢復設計會過度或不足。",
          "將每個dependency的restore/failover時間串成critical path，確認資料複寫滿足RPO。",
          "更頻繁backup降低RPO但不必然降低RTO；automation與預置容量主要影響RTO。",
          "只看database RPO，忽略event stream、object、DNS與secret的復原點。",
          "RTO is a path; RPO is a data graph",
          "應用可在一小時恢復，但付款資料最多只能遺失五分鐘。",
          "AWS Backup|AWS Elastic Disaster Recovery|AWS Resilience Hub"),
    topic(64, "Cache、Replica、Queue 與 Horizontal Scaling",
          "效能改善方法分別降低重算、分散讀取、吸收burst與增加平行capacity。",
          "先量測瓶頸：讀多用cache/replica，獨立工作水平擴展，短burst用queue。",
          "Vertical scaling是簡單過渡方案，但有上限、停機或大型instance成本。",
          "同時加入cache、replica與queue，卻無法知道哪個解決哪個metric。",
          "optimize the constrained stage, not the architecture diagram",
          "API p99慢；profile顯示80%時間等資料庫相同查詢，寫入很少。",
          "Amazon ElastiCache|RDS read replicas|Amazon SQS|Auto Scaling"),
    topic(65, "Service Quota、Throttling 與 Graceful Degradation",
          "雲端服務與下游都有quota，尖峰時成功率取決於是否在耗盡前降級。",
          "盤點quota、預先申請、監控usage，對非關鍵功能load shed並保留核心transaction。",
          "Retry可處理短暫throttle，但若arrival rate長期高於capacity只會惡化。",
          "只監控CPU，直到Lambda concurrency、NAT ports或API quota先耗盡。",
          "every architecture has a finite admission boundary",
          "促銷時圖片推薦可關閉，但結帳必須保留capacity且不得無限排隊。",
          "Service Quotas|Amazon CloudWatch|AWS Lambda"),
    topic(66, "CloudWatch Metrics、Logs、Alarms 與 Dashboards",
          "沒有可觀測性時，團隊只能從使用者抱怨猜測跨服務問題。",
          "Metrics看趨勢與告警，logs保留事件context，dashboards連接business與resource signals。",
          "High-cardinality資料不應全部變metric dimensions，可放log或trace。",
          "只告警平均CPU，忽略p99 latency、error rate、queue age與business success。",
          "observe user outcomes, then supporting resources",
          "訂單失敗率上升但所有EC2 CPU正常，SQS age與下游429正在增加。",
          "Amazon CloudWatch|CloudWatch Logs|CloudWatch Alarms"),
    topic(67, "X-Ray、Tracing 與 Bottleneck Analysis",
          "分散式request跨越多服務後，單一log無法還原延遲與因果。",
          "傳遞trace context，建立segments/subsegments，使用sampling與service map定位慢dependency。",
          "Metrics先發現影響，trace定位單次path，logs提供細節，三者互補。",
          "每個服務產生不同request ID，或100% tracing造成成本與儲存壓力。",
          "correlation IDs turn distributed events into one causal path",
          "API p99偶發三秒，平均正常，需要知道慢在Lambda、DynamoDB還是外部API。",
          "AWS X-Ray|Amazon CloudWatch|AWS Distro for OpenTelemetry"),
    topic(68, "Reserved Instances、Savings Plans 與 Spot",
          "Compute discount取決於使用承諾、instance彈性、中斷容忍與license。",
          "穩定基線用Savings Plans/RI；可中斷且可checkpoint工作用Spot；burst保留On-Demand。",
          "Capacity Reservation解決容量保證，不自動等於billing discount。",
          "將不可中斷single worker全放Spot，或依短期峰值購買三年承諾。",
          "match pricing commitment to demand certainty",
          "服務有40%穩定基線、20%日常波動與大量可重跑夜間batch。",
          "Savings Plans|Reserved Instances|EC2 Spot Instances"),
    topic(69, "Rightsizing 與 Compute Optimizer",
          "過度配置浪費成本，過小配置則造成throttling與tail latency。",
          "以長期CPU、memory、network、EBS與p95/p99資料rightsizing，配合autoscaling與load test。",
          "Compute Optimizer提供建議，但仍需理解seasonality、license與business headroom。",
          "只看平均CPU便縮小memory-bound instance，或忽略burstable credit。",
          "rightsizing is a continuous measurement loop",
          "數百台instance平均CPU低，但月末有固定高峰且部分服務受memory限制。",
          "AWS Compute Optimizer|Amazon CloudWatch|Amazon EC2"),
    topic(70, "Storage 與 Database Cost Optimization",
          "儲存成本包含容量、request、IOPS、retrieval、replica與資料搬移。",
          "利用lifecycle、compression、right storage class、gp3與database consolidation/read pattern改善。",
          "Serverless/on-demand降低閒置，但高且穩定負載可能provisioned更省。",
          "只比較每GB單價，忽略Athena掃描、Glacier取回、DynamoDB hot access與backup。",
          "optimize total cost per business operation",
          "資料湖容量便宜但每次query掃全量；DynamoDB長期穩定且on-demand帳單快速增加。",
          "Amazon S3 Lifecycle|Amazon DynamoDB|Amazon RDS|AWS Cost Explorer"),
    topic(71, "Data Transfer、NAT 與跨 AZ 成本",
          "網路費用常由架構流向而非instance價格主導。",
          "畫出每GB路徑，使用endpoint、local AZ、CloudFront與合適Region減少不必要處理與傳輸。",
          "集中式networking便於治理，但需把TGW、NAT、inspection與跨AZ每跳成本加總。",
          "Private EC2跨AZ經NAT讀S3，資料多次付費且增加failure path。",
          "cost follows bytes through every hop",
          "每月PB級S3流量經NAT，微服務也大量跨AZ聊天。",
          "NAT Gateway|AWS Transit Gateway|Amazon CloudFront|VPC endpoints"),

    topic(72, "CloudFormation 與 Infrastructure as Code",
          "手動console操作不可重現、難review，也無法可靠建立多帳號多Region環境。",
          "以template宣告desired state，參數化環境，透過stack events與rollback管理變更。",
          "CDK用程式產生CloudFormation，提升抽象但仍需理解生成template與deployment lifecycle。",
          "在production手改資源後template不知情，下一次deploy覆蓋或失敗。",
          "infrastructure changes deserve versioned code and review",
          "同一三層架構需部署dev、staging、prod與DR Region。",
          "AWS CloudFormation|AWS CDK"),
    topic(73, "Change Sets、Drift 與 Rollback",
          "IaC變更可能replacement、刪除資料或跨stack傳播，部署前需要可見差異。",
          "使用change set預覽、drift detection找手改、stack policy/deletion policy保護stateful資源。",
          "Nested stacks與StackSets改善重用/多帳號部署，但增加版本與failure scope。",
          "忽略replacement提示而重建database，或rollback時自訂resource無法復原。",
          "preview destructive transitions before execution",
          "安全基線要推全組織，但database與KMS key不得因template更新被刪除。",
          "AWS CloudFormation|CloudFormation change sets|AWS CloudFormation StackSets"),
    topic(74, "Blue/Green、Canary 與 Rolling Deployment",
          "新版本有未知風險，release strategy決定blast radius、成本與rollback速度。",
          "Canary逐步曝險，blue/green保留完整舊環境快速切回，rolling節省容量但版本混合。",
          "Database schema需expand/contract，否則compute rollback仍可能不相容。",
          "只看deployment成功而未用business metric判斷canary，或立即銷毀blue。",
          "deployment safety comes from bounded exposure and reversible state",
          "付款API需零停機、五分鐘內rollback，schema變更必須相容兩版本。",
          "AWS CodeDeploy|Elastic Load Balancing|AWS Lambda aliases"),
    topic(75, "Systems Manager、Patching 與 Fleet Management",
          "大量instance需要安全遠端操作、inventory、patch與參數管理，不能共享SSH key。",
          "使用SSM Agent、Session Manager、Patch Manager、Run Command與Automation文件。",
          "Immutable replacement可降低長期drift，但某些stateful/legacy fleet仍需in-place管理。",
          "開放22到internet並把private key傳給所有人，或批次command沒有rate/error control。",
          "prefer audited control channels over direct host access",
          "一千台private EC2需緊急patch，禁止bastion與inbound SSH。",
          "AWS Systems Manager|Session Manager|Patch Manager"),
    topic(76, "Event-driven Remediation",
          "設定偏移與安全事件若只靠人工ticket，修復時間長且結果不一致。",
          "Config/CloudTrail/EventBridge觸發Lambda或SSM Automation，先評估risk再修復並通知。",
          "高風險動作需approval與dry-run，避免自動化誤刪合法例外。",
          "Remediation形成loop反覆改回資源，卻沒有找出上游IaC或owner。",
          "automate known-safe responses, escalate ambiguous ones",
          "有人開放S3 public access，要求數分鐘內封鎖並保留完整證據。",
          "AWS Config|Amazon EventBridge|AWS Lambda|AWS Systems Manager"),
    topic(77, "Backup、Restore Testing 與 Game Day",
          "備份存在不代表應用能在目標時間恢復，依賴、權限與runbook都可能失效。",
          "定期自動restore到隔離環境，驗證資料、RTO/RPO、DNS、secret與業務交易。",
          "Game day可測failover與人員流程，但需guardrails和停止條件。",
          "只測database restore，忽略application version、KMS key與event replay。",
          "reliability claims require exercised evidence",
          "稽核要求證明每季可從跨帳號vault恢復完整付款流程。",
          "AWS Backup|AWS Fault Injection Service|AWS Resilience Hub"),
    topic(78, "Operational Excellence 與 Continuous Improvement",
          "架構不是一次性圖紙；runbook、指標、事件與改進backlog共同決定長期品質。",
          "定義owner、operational readiness review、SLO、alarm、runbook、postmortem與定期Well-Architected review。",
          "Managed service降低部分toil，但service quota、cost、security與application failure仍需ownership。",
          "每次事故只增加更多alarm，造成noise而沒有移除根因。",
          "operations is a feedback system, not a support phase",
          "快速成長團隊每週事故增加，alarms數百個但on-call不知道先處理什麼。",
          "AWS Well-Architected Tool|Amazon CloudWatch|AWS Systems Manager"),
]
