"""Topics 79–116: enterprise, AI, case studies, and portable patterns."""
from aws_architect_topic_factory import topic


TOPICS = [
    topic(79, "Landing Zone 與 Multi-account Strategy",
          "企業需要以帳號隔離billing、quota、權限與blast radius，同時保留一致治理。",
          "依business unit、environment與data sensitivity設計OU/account，Control Tower建立landing zone。",
          "單帳號起步簡單，但規模後policy、quota與事故隔離難以管理。",
          "把OU當網路邊界，或帳號切得太碎卻沒有自動供應與lifecycle。",
          "accounts are strong operational and security boundaries",
          "企業併購後有數百工作負載，需統一安全基線但讓團隊獨立交付。",
          "AWS Organizations|AWS Control Tower|AWS Account Factory",
          "SAP"),
    topic(80, "Centralized Network 與 Inspection VPC",
          "大型組織需要shared connectivity、egress control與流量檢查，但中央化會形成關鍵路徑。",
          "TGW連接spokes，route tables分段，inspection VPC使用Network Firewall/GWLB並確保對稱路由。",
          "每VPC自治egress降低中央依賴，但policy、cost與audit較分散。",
          "所有流量經單AZappliance，return path不對稱或中央NAT超載。",
          "centralize policy while distributing capacity and failure domains",
          "Prod、dev與partner networks需不同route domain，internet流量必須集中稽核。",
          "AWS Transit Gateway|AWS Network Firewall|Gateway Load Balancer",
          "SAP"),
    topic(81, "Centralized Logging 與 Security Accounts",
          "攻擊者取得workload帳號後不應能刪除稽核證據或停用偵測。",
          "建立log archive與security tooling帳號，Organizations整合CloudTrail、Config、GuardDuty與Security Hub。",
          "各帳號保留操作view可加速回應，但authoritative copies應跨帳號不可變保存。",
          "Log bucket policy允許source帳號刪除，或所有security admin都使用management account。",
          "security evidence must outlive the compromised account",
          "SOC需查詢全組織API與finding，工作負載管理者不得修改歷史log。",
          "AWS CloudTrail|AWS Config|Amazon GuardDuty|AWS Security Hub",
          "SAP"),
    topic(82, "Enterprise Identity 與 Cross-account Authorization",
          "數千員工、automation與第三方需要不同身份生命週期與權限委派。",
          "Workforce federation經Identity Center；workload使用roles；第三方使用external ID與最小trust。",
          "ABAC可依tag擴展授權，但需防止使用者自行修改高信任attribute。",
          "每帳號local user、shared automation key與永久Administrator role。",
          "identity lifecycle should be centralized; authorization stays contextual",
          "公司目錄有部門與職級屬性，需動態授予數百帳號不同權限。",
          "AWS IAM Identity Center|AWS STS|IAM ABAC",
          "SAP"),
    topic(83, "Global Application 與 Multi-Region Data",
          "全球架構要同時處理route、compute、data consistency、write ownership與failover。",
          "依資料語意選single-writer、read-local、active-active或partitioned ownership，再選Route 53/GA與data service。",
          "只將stateless compute active-active可先改善availability，而不必立即讓所有database多主。",
          "DNS切換後新Region沒有最新secret、event offsets或寫入權，造成split brain。",
          "global compute is easier than global mutable state",
          "SaaS需全球低延遲讀取，但帳務寫入不可衝突且Region故障可接管。",
          "Amazon Route 53|AWS Global Accelerator|Aurora Global Database|DynamoDB Global Tables",
          "SAP"),
    topic(84, "Organization-wide Backup、DR 與 Compliance",
          "各團隊自行備份會產生不一致retention、未加密副本與無人測試的restore。",
          "用AWS Backup policies跨帳號套用、copy到隔離vault/Region並集中audit。",
          "Service-native backup提供更細能力，仍可由組織policy建立最低基線。",
          "Backup role可被workload admin刪除，或KMS key與backup同一故障邊界。",
          "recovery assets need independent ownership",
          "勒索風險要求所有production database具跨帳號immutable copy與季度restore證明。",
          "AWS Backup|Backup Vault Lock|AWS Organizations",
          "SAP"),
    topic(85, "Portfolio Cost、Tagging 與 Chargeback",
          "單一帳單無法回答哪個產品、環境或團隊消耗成本，也無法建立責任。",
          "Organizations consolidated billing配合cost allocation tags、CUR、Budgets與account boundaries。",
          "Showback先提高可見度，chargeback再將成本計入決策；兩者都需穩定taxonomy。",
          "只靠資源Name tag，或共享平台成本全部歸中央而讓consumer看不到邊際成本。",
          "cost allocation is an ownership model",
          "CFO需按產品與客戶分攤共享TGW、data lake與support成本。",
          "AWS Cost and Usage Report|AWS Cost Explorer|AWS Budgets",
          "SAP"),
    topic(86, "Migration Assessment、Portfolio 與 Wave Planning",
          "大型migration不是逐台server搬移；application dependency與business calendar決定風險。",
          "建立inventory、dependency map、business case與wave plan，先搬低風險並建立migration factory。",
          "Application Discovery Service提供資料，但owner訪談與實際traffic仍需交叉驗證。",
          "依server數量排wave，拆開強耦合應用，cutover後才發現隱藏dependency。",
          "migrate dependency groups, not asset lists",
          "兩千台server需十八個月搬完，部分系統共享database與批次檔案。",
          "AWS Migration Hub|AWS Application Discovery Service|Migration Evaluator",
          "SAP"),
    topic(87, "Application Migration Service、DMS 與 SCT",
          "Server、database engine與schema/code conversion需要不同migration工具。",
          "MGN持續block replication搬server；DMS搬資料並持續CDC；SCT評估/轉換schema與code。",
          "DataSync處理file/object，Snow處理離線資料，不能取代transactional CDC。",
          "只測initial load，cutover時CDC lag未歸零或unsupported objects未轉換。",
          "separate compute replication, data movement, and semantic conversion",
          "Oracle應用先rehost EC2，database改Aurora PostgreSQL並要求短停機。",
          "AWS Application Migration Service|AWS DMS|AWS Schema Conversion Tool",
          "SAP"),
    topic(88, "7Rs：Rehost 到 Refactor",
          "每個workload的business value、技術債與時間限制不同，不應全部refactor。",
          "用retain/retire/relocate/rehost/replatform/repurchase/refactor逐一決策並記錄理由。",
          "Rehost速度快但保留營運問題；refactor收益高但風險與時間最大。",
          "把modernization當migration前置條件，導致data center exit期限失敗。",
          "migration strategy is a portfolio optimization problem",
          "資料中心租約九個月到期，但只有20%核心系統值得立即重構。",
          "AWS Migration Hub|AWS Application Migration Service",
          "SAP"),
    topic(89, "Monolith 到 Containers／Serverless",
          "Modernization需要找到可獨立演進邊界，而不是把monolith機械切成大量服務。",
          "先strangler邊緣功能，建立API/event contract，將state與deployment逐步分離。",
          "Containerize可先改善部署一致性；serverless適合事件與變動流量，但不自動解耦domain。",
          "共享database的微服務仍高度耦合，且distributed transaction讓可靠性下降。",
          "modernize around ownership and change boundaries",
          "大型Java monolith每季發布，團隊想逐步讓付款與通知獨立交付。",
          "Amazon ECS|Amazon EKS|AWS Lambda|Amazon API Gateway",
          "SAP"),
    topic(90, "持續改善既有系統",
          "SAP常不是從空白設計，而是要求在最少風險下改善安全、可靠、效能與成本。",
          "先建立baseline與business priority，再找最大風險、設計reversible change並量測結果。",
          "一次全面重寫可能消除部分技術債，但失去漸進驗證與rollback。",
          "只因服務較新就遷移，沒有證明改善哪個SLO、成本或control gap。",
          "continuous improvement is hypothesis-driven architecture",
          "現有平台穩定但昂貴、部署慢且跨帳號權限過寬，不能長時間停機。",
          "AWS Well-Architected Tool|AWS Compute Optimizer|AWS Config",
          "SAP"),

    topic(91, "Amazon Bedrock 基礎架構",
          "Generative AI應用除模型呼叫外，還包含identity、data retrieval、guardrails、latency與cost。",
          "使用Bedrock managed foundation models，將prompt、knowledge base、agent tools與observability分層。",
          "SageMaker AI適合更完整自建訓練/hosting控制；Bedrock偏foundation model應用API。",
          "把prompt中的敏感資料無條件送模型，或未限制agent tool permissions。",
          "AI applications are distributed systems with probabilistic components",
          "企業客服需RAG、內容過濾、private data與每次回答來源。",
          "Amazon Bedrock|Amazon Bedrock Knowledge Bases|Amazon Bedrock Agents",
          "SAP Emerging"),
    topic(92, "Generative AI Data Security",
          "Prompt、retrieval document、embedding、log與model output都可能包含敏感資料。",
          "分類資料、最小化傳送、加密、隔離tenant、限制logging並以IAM控制model與knowledge base。",
          "Private connectivity可降低internet exposure，但不能取代authorization與data filtering。",
          "將完整customer record放入prompt，trace/log永久保存且所有開發者可讀。",
          "treat prompts and outputs as sensitive data flows",
          "醫療助理需引用病歷，但不同醫院tenant不得互見，debug log不能保存完整內容。",
          "Amazon Bedrock|AWS KMS|AWS PrivateLink|Amazon Macie",
          "SAP Emerging"),
    topic(93, "Bedrock Guardrails 與 Responsible AI",
          "模型可能產生不當、越權、個資或不符合政策的內容。",
          "在input/output套Guardrails、topic/policy filters與denied content，並為拒絕與誤判建立人工流程。",
          "Guardrails是防禦層，不取代資料授權、prompt injection防護與business validation。",
          "只在UI過濾output，tool action已先執行；或沒有版本化policy與測試集。",
          "probabilistic systems need deterministic policy gates",
          "金融助理不得給未核准投資建議，也不能顯示個資或執行高風險交易。",
          "Amazon Bedrock Guardrails|AWS Step Functions",
          "SAP Emerging"),
    topic(94, "Agent Identity 與 Tool Authorization",
          "Agent代表使用者呼叫工具時，必須保留requester identity、scope與audit，而非使用共享admin role。",
          "以AgentCore Identity或短期delegated credentials，對每個tool定義最小action/resource/condition。",
          "中央broker可簡化token exchange，但需避免變成全能credential vault。",
          "所有agent共用長期access key，prompt injection即可取得跨tenant權限。",
          "an agent must never be more authorized than the represented intent",
          "客服agent可退款自己的customer ticket，但不可查詢其他region或提高退款上限。",
          "Amazon Bedrock AgentCore Identity|AWS STS|IAM",
          "SAP Emerging"),
    topic(95, "Human-in-the-loop Approval",
          "高風險AI action不能只依模型信心自動執行，需要可追蹤的人工核准。",
          "Step Functions暫停workflow、發送approval token、限制期限並保存輸入/決策/audit。",
          "低風險、可逆action可自動化；風險與金額提高時升級人工。",
          "人工只收到『approve?』沒有evidence，或approval link可被重放。",
          "automation authority should scale with reversibility and evidence",
          "AI建議刪除資源或批准高額退款，必須由具權限人員確認。",
          "AWS Step Functions|Amazon SNS|Amazon API Gateway",
          "SAP Emerging"),
    topic(96, "AI Observability、Cost 與 Failure Isolation",
          "AI response可能因model、retrieval、tool、prompt或policy失敗，token成本與延遲也會快速變動。",
          "分段量測retrieval quality、model latency/token、tool success、guardrail reject與business outcome。",
          "Cache可降低重複推論成本，但需處理tenant、staleness與敏感資料。",
          "只監控HTTP 200而忽略hallucination、tool side effect與每成功任務成本。",
          "evaluate quality, safety, latency, and cost as separate signals",
          "Agent成功回應但引用錯誤文件，且token成本在新prompt後增加三倍。",
          "Amazon Bedrock|Amazon CloudWatch|AWS X-Ray",
          "SAP Emerging"),

    topic(97, "Case Study：全球電商平台",
          "全球電商同時要求低延遲、庫存一致、付款冪等、促銷burst與跨Region DR。",
          "Edge cache靜態內容，regional stateless services，queue吸收非同步工作，交易資料定義single writer/replication。",
          "全active-active可降低部分延遲，但庫存與付款衝突處理會大幅增加。",
          "將每個服務同步串接，推薦失敗便阻止checkout，或重試造成重複付款。",
          "separate browse availability from transaction correctness",
          "平日一萬RPS，促銷十倍；付款不能重複，推薦可降級。",
          "Amazon CloudFront|Application Load Balancer|Amazon Aurora|Amazon SQS|AWS WAF"),
    topic(98, "Case Study：Serverless SaaS",
          "多租戶SaaS需要tenant isolation、burst scaling、成本歸屬與安全onboarding。",
          "API Gateway/Lambda處理request，DynamoDB以tenant-aware keys，per-tenant quota與idempotency控制。",
          "Pool model成本低；silo model隔離強；bridge model依tenant tier混合。",
          "只在request body相信tenant ID，或單一hot tenant耗盡整個Lambda concurrency。",
          "multi-tenancy is an isolation and noisy-neighbor design",
          "數千小客戶共享平台，少數enterprise要求獨立key與資料邊界。",
          "Amazon API Gateway|AWS Lambda|Amazon DynamoDB|AWS KMS"),
    topic(99, "Case Study：高流量影音服務",
          "影音平台需要大物件ingest、transcode、全球delivery與成本控制。",
          "S3保存source/output，event觸發queue/batch轉檔，CloudFront edge delivery並用signed URL。",
          "Media services可降低自建轉碼複雜度；自建GPU提供特殊codec控制。",
          "Origin直接服務全球下載，或轉檔job沒有idempotency造成重複成本。",
          "move bytes once, transform asynchronously, serve from the edge",
          "每天上傳TB影片，熱門內容全球觀看，冷內容保存多年。",
          "Amazon S3|Amazon CloudFront|AWS Batch|AWS Elemental MediaConvert"),
    topic(100, "Case Study：金融多帳號環境",
          "金融組織需強身份、不可變稽核、網路分段、資料加密與一致guardrails。",
          "Control Tower landing zone、Identity Center、central security/log accounts、SCP與inspection network。",
          "分散治理可加快團隊，但底線controls必須不可繞過且有例外流程。",
          "Security tooling全在management account，或SCP阻止incident response role。",
          "governance must preserve both prevention and recovery access",
          "五十個產品團隊受監管，必須證明所有帳號CloudTrail、加密與備份符合政策。",
          "AWS Control Tower|AWS Organizations|AWS Security Hub|AWS KMS"),
    topic(101, "Case Study：Hybrid Enterprise Migration",
          "企業migration期間要同時維持on-premises與AWS，dependency、DNS、identity與network會長期共存。",
          "建立DX/VPN冗餘、hybrid DNS、wave plan、MGN/DMS，逐波驗證並保留rollback。",
          "Big-bang可縮短共存期但集中風險；長期hybrid則增加雙環境營運。",
          "CIDR重疊、DNS split horizon錯誤與未發現hard-coded IP阻塞cutover。",
          "migration architecture is temporary production architecture",
          "兩個資料中心一年內關閉，四百應用分批搬移且部分需主機大型機。",
          "AWS Direct Connect|AWS Migration Hub|AWS Application Migration Service|AWS DMS"),
    topic(102, "Case Study：Data Lake 與即時分析",
          "同一平台需接batch/stream、保存raw、治理schema與權限，並支援BI/ML。",
          "S3分層保存，Glue catalog，Lake Formation治理，Kinesis/MSK ingest，Athena/Redshift查詢。",
          "單一warehouse簡單但不適合所有raw與低成本長期保存。",
          "缺乏partition/schema contract導致small files、昂貴scan與跨團隊資料洩漏。",
          "a data platform separates immutable facts from derived serving layers",
          "每秒百萬事件、每日批次ERP資料、分析師與ML團隊需不同權限。",
          "Amazon S3|AWS Glue|AWS Lake Formation|Amazon Kinesis|Amazon Redshift"),
    topic(103, "Case Study：Multi-Region DR",
          "跨Region DR不是複製database就完成，還包括build、identity、network、DNS與operations。",
          "以RTO/RPO選warm standby，持續複寫state、IaC建立環境、定期game day驗證切換與回切。",
          "Backup/restore成本更低，若business可接受較長RTO應優先。",
          "Failover成功但舊Region仍接受write，恢復後資料分叉。",
          "failover requires fencing, validation, and failback",
          "核心服務RTO 30分鐘、RPO 5分鐘，法規要求每半年演練。",
          "Amazon Route 53|AWS Backup|Aurora Global Database|AWS CloudFormation"),
    topic(104, "Case Study：AI Agent Application",
          "Agent需存取企業資料與工具，model output不確定但side effect必須受控。",
          "Bedrock模型/RAG與tool execution分層，identity綁定user，Guardrails過濾，Step Functions核准高風險action。",
          "純chatbot不執行工具時風險較低；agentic workflow需要更完整audit與idempotency。",
          "Model直接持admin credentials，或tool成功但response timeout後重複執行。",
          "probabilistic planning must terminate at deterministic authorization",
          "IT agent可查詢與重啟service，高風險production操作需人工批准。",
          "Amazon Bedrock|Amazon Bedrock Guardrails|AWS Step Functions|AWS STS"),

    topic(105, "Managed Service 優先與 Escape Hatch",
          "自行營運基礎元件能獲得控制，但會承擔patch、HA、backup、upgrade與on-call。",
          "先選滿足需求的最高managed abstraction，同時確認limits、data portability與離開路徑。",
          "自管適合供應商未支援的protocol、性能或合規需求，但要估完整人力成本。",
          "把managed service當無限制黑盒，直到quota或feature gap才發現沒有替代方案。",
          "buy undifferentiated operations; retain control over differentiating contracts",
          "團隊考慮自建Kafka/RDS替代品，只因單價看似較低。",
          "Amazon RDS|Amazon MSK|AWS Fargate"),
    topic(106, "Decouple Independently Scalable Components",
          "若前後端必須同步同時成功、同時擴展，一個慢元件會限制整體。",
          "以queue/event/API contract分離rate、deployment與failure，讓consumer依自己capacity處理。",
          "同步仍適合需要即時確認的短路徑，不必為所有呼叫引入eventual consistency。",
          "只把同步request包進queue卻仍阻塞等待，增加元件但沒有真正解耦。",
          "decoupling is independent change, scale, and failure",
          "圖片上傳後縮圖與內容審核可晚幾秒完成，不能拖慢upload response。",
          "Amazon SQS|Amazon EventBridge|AWS Step Functions"),
    topic(107, "Eliminate Single Points of Failure",
          "單點不只是一台server，也可能是AZ、NAT、identity provider、deployment pipeline或人。",
          "列出每個critical path dependency，跨適當failure domain部署並測試自動替換。",
          "有些control plane可接受較長恢復，data plane則需持續服務，兩者SLO不同。",
          "前端多AZ但database、NAT或KMS policy只有單一可用路徑。",
          "availability is the product of every required dependency",
          "架構圖有三台EC2，但所有流量與資料仍依賴單一AZ元件。",
          "Availability Zones|Elastic Load Balancing|Amazon RDS"),
    topic(108, "Blast Radius 與 Cell-based Architecture",
          "全域共享資源提高效率，也讓單一bug或overload影響所有租戶。",
          "以account、Region、cell、tenant shard分隔容量與deployment，global layer只做必要routing。",
          "更多cells增加容量浪費、資料搬移與控制面複雜度。",
          "Shared queue/database沒有tenant限額，一個客戶拖垮全平台。",
          "partition failure domains before the incident chooses them",
          "SaaS需讓單一region或enterprise tenant事故最多影響一小部分使用者。",
          "AWS Organizations|Amazon Route 53|Amazon DynamoDB"),
    topic(109, "Queue 吸收 Burst，而非無限 Overload",
          "Queue能把短期arrival spike平滑成可處理速率，但長期超載只會累積過期工作。",
          "使用bounded backlog、queue age SLO、autoscaling、admission control與load shedding。",
          "增加retention爭取處理時間，但不會提升consumer capacity。",
          "只看queue depth不看age與deadline，系統仍處理已無價值的request。",
          "buffers buy time; they do not create throughput",
          "Producer長期每秒一萬件，consumer只能八千，queue每天持續增長。",
          "Amazon SQS|Amazon Kinesis|Amazon CloudWatch"),
    topic(110, "Cache 不是正確性來源",
          "Cache副本可能過期、evict或部分失效，business correctness不能依賴它永久存在。",
          "定義authoritative store、TTL/invalidation、miss path與stampede protection。",
          "Write-through/read-through可簡化應用，但仍需處理partial failure。",
          "Cache miss被當不存在，造成授權或庫存錯判。",
          "a cache may accelerate truth but must not redefine it",
          "權限cache延遲更新可能讓已撤權使用者繼續存取。",
          "Amazon ElastiCache|Amazon CloudFront|DAX"),
    topic(111, "Control Plane 與 Data Plane 分離",
          "管理設定與處理每個request的路徑有不同availability、latency與一致性需求。",
          "Data plane使用已發布、可cache的configuration；control plane更新需版本化、驗證與漸進發布。",
          "強一致control lookup每request執行較直觀，但會把管理服務變成runtime單點。",
          "控制面短暫不可用導致既有資料面也停止服務。",
          "serve from local published state; manage through slower verified workflows",
          "Feature flag服務故障時，應用應維持最後已知安全設定。",
          "Amazon Route 53|AWS AppConfig|AWS Systems Manager"),
    topic(112, "Identity、Network、Data 三層安全",
          "單一防火牆或IAM policy無法同時處理身份、路徑與資料生命週期。",
          "Identity限制誰可做什麼，network限制可達路徑，data controls加密、分類、備份與retention。",
          "Defense in depth不是重複相同規則，而是不同失效模式的獨立控制。",
          "Private subnet被當作授權，任何已進VPC的principal都能讀敏感資料。",
          "security boundaries should fail independently",
          "內部分析服務在private VPC，但仍需tenant authorization與column-level保護。",
          "IAM|Amazon VPC|AWS KMS|AWS Lake Formation"),
    topic(113, "Observability 跟隨 Business Outcome",
          "資源健康不代表使用者成功，CPU正常時付款仍可能因第三方失敗。",
          "先定義business transaction success/latency，再向下連接service與resource signals。",
          "Synthetic monitoring驗證外部path，real-user telemetry反映實際分布。",
          "Dashboard充滿host metrics但沒有訂單成功率、lag或資料新鮮度。",
          "measure what users need, then explain it with internals",
          "所有Lambda invocation成功，但事件晚兩小時處理，使用者看到過期資料。",
          "Amazon CloudWatch|AWS X-Ray|CloudWatch Synthetics"),
    topic(114, "RTO/RPO 決定 DR，而非服務名稱",
          "相同AWS服務可組成不同恢復能力，真正contract來自資料流與演練。",
          "先分解資料與dependency的RPO/RTO，再選backup、replication、standby與routing。",
          "Service SLA與DR目標相關但不等價；application還有部署與操作時間。",
          "購買Global Database便宣稱RTO為零，沒有automation、fencing與runbook。",
          "recovery objectives are end-to-end properties",
          "Database可秒級promotion，但DNS、secret與人工核准使整體恢復需兩小時。",
          "AWS Backup|Aurora Global Database|Amazon Route 53"),
    topic(115, "Cost 是 Architecture Constraint",
          "成本不是設計完成後才清理；data path、availability與營運選擇一開始就決定大部分支出。",
          "以每transaction、tenant或GB的unit economics比較方案，將固定與變動成本分開。",
          "最低帳單不一定最佳，還要包含人力、風險、遷移與機會成本。",
          "只靠RI降低費用，沒有修正跨AZ流量、閒置資料與無限retention。",
          "architecture is economics expressed as technical structure",
          "兩方案月費相近，但其中一個需要兩名工程師全年維護cluster。",
          "AWS Cost Explorer|AWS Cost and Usage Report|AWS Compute Optimizer"),
    topic(116, "Migration 由 Business Value 與 Dependency Graph 驅動",
          "技術上可搬的順序不一定創造價值，也可能切斷高耦合dependency。",
          "以business outcome、風險、dependency與學習價值排序waves，完成後量測benefit。",
          "先搬簡單系統可建立能力，但若完全不碰代表性dependency就無法驗證factory。",
          "Migration成功定義成server已啟動，卻沒有關閉data center或改善SLO/成本。",
          "migration completes when the business operating model changes",
          "公司要退出機房、提高發布速度並降低license，不只是複製VM。",
          "AWS Migration Hub|AWS Application Migration Service|AWS Well-Architected Tool"),
]
