"""Concrete AWS component knowledge used by every chapter.

The profiles intentionally focus on architecture contracts: what the component
does, the mechanism that makes it work, the settings candidates must recognize,
and the boundary where another component becomes a better fit.
"""
from __future__ import annotations

from dataclasses import dataclass

from aws_architect_model import Topic


@dataclass(frozen=True)
class ComponentProfile:
    purpose: str
    mechanism: str
    config: str
    choose: str
    replace: str


def P(
    purpose: str,
    mechanism: str,
    config: str,
    choose: str,
    replace: str,
) -> ComponentProfile:
    return ComponentProfile(purpose, mechanism, config, choose, replace)


PROFILES: dict[str, ComponentProfile] = {
    "AWS Certification": P(
        "以公開exam guide驗證特定job role所需的AWS架構能力。",
        "Exam domains/tasks定義coverage，題目以scenario測服務選型與trade-off，而非要求背CLI語法。",
        "exam version、domain weights、task statements、in-scope services與官方sample questions。",
        "建立讀書範圍、弱點矩陣與mock review loop。",
        "服務實際行為仍以產品文件為準，不能把study guide當產品規格。",
    ),
    "AWS Well-Architected Framework": P(
        "用六個pillars系統化檢視workload架構與營運風險。",
        "以questions、best practices與improvement plan把business context映射到security、reliability等trade-offs。",
        "workload definition、milestones、pillar questions、high-risk issues與improvement priorities。",
        "設計審查、現有系統改善與SAP多constraint scenario。",
        "它是決策框架，不會自動部署controls或修復resources。",
    ),
    "AWS Well-Architected Tool": P(
        "在AWS中記錄Well-Architected reviews、milestones與improvement plans。",
        "Workload套用lenses回答questions，工具標示high/medium risk並追蹤改進。",
        "workload、Regions、lenses、milestones、profiles、sharing與improvement items。",
        "需要重複、可稽核的architecture review process。",
        "工具輸出依賴輸入品質；仍需metrics、tests與domain experts驗證。",
    ),
    "Shared Responsibility Model": P(
        "區分AWS負責cloud infrastructure與customer負責cloud內資料、身份、設定及workload。",
        "責任隨IaaS、container與managed/serverless抽象移動，但customer永遠保留資料分類與access決策。",
        "service abstraction、data owner、IAM、network exposure、encryption、patching與logging responsibility。",
        "判斷某個安全或營運工作應由誰完成。",
        "Managed不等於免責；若需要OS控制，選EC2也同時接回patch/hardening責任。",
    ),
    "AWS Regions": P(
        "隔離資料、控制合規位置，並提供跨地理區域的服務部署邊界。",
        "每個Region有獨立的服務control plane、quota與多個AZ；資料通常不會自動跨Region複製。",
        "Region選擇、service availability、data residency、cross-Region replication與transfer cost。",
        "法規、使用者延遲、DR或服務可用性要求必須指定地理位置時。",
        "只需抵抗單一資料中心故障時先用Multi-AZ，避免過早承擔跨Region一致性與成本。",
    ),
    "Availability Zones": P(
        "在同一Region內提供可彼此隔離的資料中心級failure domains。",
        "AZ以低延遲私有網路互連；把副本與compute分散到AZ可抵抗單一AZ故障。",
        "subnet AZ、Auto Scaling distribution、Multi-AZ、cross-zone load balancing與cross-AZ cost。",
        "幾乎所有production regional workload的第一層高可用設計。",
        "需要抵抗整個Region中斷或資料主權需求時，升級為Multi-Region。",
    ),
    "Amazon CloudFront": P(
        "在edge快取與代理HTTP內容，降低全球使用者延遲並保護origin。",
        "DNS把使用者導向edge POP；cache key、TTL與origin policy決定何時命中或回源。",
        "origins、cache policy、origin request policy、behaviors、OAC、TTL、WAF與geo restriction。",
        "可快取的HTTP內容、S3私有origin、全球網站、API加速與edge security。",
        "需要非HTTP的TCP/UDP加速或固定anycast IP時選Global Accelerator。",
    ),
    "AWS Global Accelerator": P(
        "以兩個static anycast IP把TCP/UDP流量導入AWS全球骨幹並做健康端點切換。",
        "Anycast將client送到最近edge，再依endpoint group、weight與health導向regional endpoint。",
        "listeners、endpoint groups、traffic dial、endpoint weight、health checks與client affinity。",
        "遊戲、VoIP、IoT、固定IP allowlist或不可快取的全球TCP/UDP應用。",
        "HTTP內容需要cache、header/path routing或edge function時選CloudFront。",
    ),
    "Lambda@Edge": P(
        "在CloudFront edge事件上執行Lambda程式，依request/response修改header、URI、認證或origin選擇。",
        "CloudFront在viewer request、origin request、origin response或viewer response階段呼叫已複寫到edge的函式版本。",
        "event trigger、us-east-1 function version、IAM execution role、memory/timeout、include body、logs與deployment restrictions。",
        "需要依viewer request做輕量認證、URL rewrite、header處理或動態origin selection時。",
        "只需簡單低延遲JavaScript處理可比較CloudFront Functions；完整API/business logic應放regional service。",
    ),
    "Amazon EC2": P(
        "提供可控制OS、runtime、network與storage的虛擬機compute。",
        "Nitro hypervisor隔離instance；AMI建立root volume，ENI連VPC，instance profile提供temporary credentials。",
        "instance family/size、AMI、subnet、security group、IAM instance profile、user data、tenancy與purchase option。",
        "需要OS存取、legacy agent、特定driver、長時間process或自訂network/storage時。",
        "只需執行container選ECS/EKS/Fargate；短事件工作選Lambda以降低主機營運。",
    ),
    "Amazon EC2 Auto Scaling": P(
        "依健康狀態與需求訊號維持、替換並調整EC2 fleet。",
        "Launch template定義instance；Auto Scaling group跨subnets放置，policy改變desired capacity並執行health replacement。",
        "min/max/desired、launch template、subnets、health check grace、instance warmup、target tracking、mixed instances與lifecycle hooks。",
        "stateless EC2水平擴展、Multi-AZ replacement、Spot/On-Demand混合容量。",
        "它不分配client traffic，通常搭配ELB；container service使用ECS/EKS service autoscaling。",
    ),
    "Amazon ECS": P(
        "以AWS原生control plane排程與維護containers。",
        "Task definition描述image、CPU/memory、ports與roles；service scheduler維持desired count並整合LB。",
        "task definition、taskRoleArn、executionRoleArn、networkMode、capacity provider、service deployment與health check。",
        "團隊要container但不需要Kubernetes API與生態相容性時。",
        "既有Kubernetes工具鏈選EKS；短事件函式選Lambda；不想管理nodes可搭配Fargate。",
    ),
    "Amazon EKS": P(
        "提供managed Kubernetes control plane與AWS整合。",
        "AWS管理高可用API server/etcd；pods由managed node groups、self-managed nodes或Fargate執行。",
        "cluster endpoint access、node groups、IRSA/Pod Identity、CNI、add-ons、taints與pod disruption budget。",
        "需要Kubernetes API、生態、portable manifests、operators或既有平台技能時。",
        "不需要Kubernetes複雜度時以ECS降低營運；單一事件handler可用Lambda。",
    ),
    "AWS Fargate": P(
        "讓ECS或EKS task/pod在不管理EC2 nodes的情況下執行。",
        "AWS在隔離的microVM容量上放置工作；使用者仍設定每個task的CPU、memory、network與IAM。",
        "task CPU/memory組合、awsvpc、subnets/security groups、ephemeral storage與platform version。",
        "bursty containers、小平台團隊、每個task需獨立ENI與按使用量付費時。",
        "穩定高利用率或需GPU、特殊daemon/host access時改用EC2-backed ECS/EKS。",
    ),
    "AWS Lambda": P(
        "按事件執行短生命函式，自動管理capacity與runtime基礎設施。",
        "事件觸發execution environment；concurrency是同時執行數，環境可能重用但不可當durable state。",
        "memory/CPU、timeout、reserved/provisioned concurrency、event source mapping、DLQ/destination、VPC與ephemeral storage。",
        "事件驅動、不可預測流量、短工作、API或資料轉換，且希望最少主機營運時。",
        "長時間process、持久connection、特殊OS/driver或穩定高利用率時選container/EC2。",
    ),
    "Amazon VPC": P(
        "建立Region內可控制CIDR、subnet、route與network policy的邏輯網路。",
        "ENI取得subnet IP；route table選下一跳；SG/NACL分別在ENI與subnet邊界過濾。",
        "IPv4/IPv6 CIDR、subnets、route tables、DHCP options、DNS support/hostnames、flow logs與tenancy。",
        "任何需要私有位址、network segmentation或hybrid connectivity的workload。",
        "跨大量VPC的服務到服務連線可用PrivateLink/VPC Lattice，避免建立完全互通網路。",
    ),
    "AWS VPC IP Address Manager": P(
        "跨accounts與Regions規劃、分配、監控IP address space。",
        "以IPAM pools階層委派CIDR，追蹤utilization、overlap與compliance。",
        "operating Regions、scope、top-level/child pools、allocation rules、locale、sharing與monitoring。",
        "大型organization、自動account vending與hybrid CIDR避免重疊。",
        "少量單一VPC可人工規劃；IPAM不取代route tables或DNS。",
    ),
    "CIDR": P(
        "用prefix長度定義IP位址範圍，決定可用位址與route匹配粒度。",
        "每增加一個prefix bit，位址數減半；route採longest-prefix match。",
        "primary/secondary VPC CIDR、subnet CIDR、non-overlap planning、IPv6 /56與prefix lists。",
        "建立VPC、subnet、hybrid route與未來network growth plan時。",
        "大量帳號容易衝突時以VPC IPAM集中配置與稽核。",
    ),
    "Subnets": P(
        "把VPC CIDR切成單一AZ內的IP與路由邊界。",
        "Subnet本身不叫public/private；是否有到IGW的route及instance是否有public IP才決定internet path。",
        "AZ、CIDR、route-table association、NACL、auto-assign public IP與available IP capacity。",
        "分散AZ、隔離web/app/data tiers或建立inspection/egress路徑時。",
        "只用security group做workload微分段時不必為每個小角色建立過多subnet。",
    ),
    "Route tables": P(
        "決定subnet或gateway流量的下一跳。",
        "先匹配目的CIDR，再選最長prefix；local route允許VPC內互通，其他target可為IGW/NAT/TGW/endpoint。",
        "destination CIDR/prefix list、target、association、propagation、blackhole與return route。",
        "建立public/private/inspection/hybrid data path與故障隔離時。",
        "需要application-aware routing時使用ALB、API Gateway或service mesh，而不是L3 route。",
    ),
    "Internet Gateway": P(
        "讓具有public IP的VPC資源與Internet雙向通訊。",
        "IGW是水平擴展的VPC gateway，對instance public IPv4做一對一NAT並依route傳遞。",
        "VPC attachment、0.0.0.0/0或::/0 route、public IP/EIP、SG與NACL return path。",
        "public load balancer、bastion或真正需要直接Internet入口的資源。",
        "private instances只需outbound IPv4時使用NAT Gateway；AWS service存取優先用VPC endpoint。",
    ),
    "NAT Gateway": P(
        "讓private subnet的IPv4資源主動對外，拒絕Internet主動建立的入站連線。",
        "在特定AZ配置NAT並以source NAT轉換connection；private route把default route指向NAT。",
        "public/private NAT type、subnet、EIP、per-AZ route、connection/port capacity與CloudWatch metrics。",
        "private workload必須下載更新或呼叫無private endpoint的public API時。",
        "S3/DynamoDB使用gateway endpoint、其他AWS服務使用interface endpoint，可減少NAT cost與failure dependency。",
    ),
    "VPC endpoints": P(
        "讓VPC私下存取AWS服務，不經IGW或NAT。",
        "Gateway endpoint把S3/DynamoDB prefix route加入route table；interface endpoint以PrivateLink ENI與private DNS接服務。",
        "service name、endpoint type、subnets、security groups、private DNS、route tables與endpoint policy。",
        "要求private connectivity、降低NAT成本或用endpoint policy建立額外data perimeter時。",
        "VPC間完整雙向routing選Peering/TGW；只發布特定服務選PrivateLink。",
    ),
    "AWS PrivateLink": P(
        "以interface endpoint私下發布或消費特定服務，而不暴露整個VPC route domain。",
        "Provider以NLB和endpoint service發布；consumer在自己的subnet取得endpoint ENI。",
        "endpoint service acceptance、allowed principals、NLB、interface endpoint subnets/SG、private DNS。",
        "SaaS、跨帳號服務、CIDR重疊或只需單向client-to-service連線時。",
        "需要VPC任意IP雙向互通用Peering/TGW；需要L7服務網路可評估VPC Lattice。",
    ),
    "Security groups": P(
        "在ENI層提供stateful allow-only虛擬防火牆。",
        "允許的connection回程自動放行；規則可引用CIDR、prefix list或另一SG。",
        "inbound/outbound protocol、port、source/destination、SG referencing與rule descriptions。",
        "以workload身份控制ALB→app→DB的least-privilege路徑。",
        "需要explicit deny、subnet邊界或無狀態規則時使用NACL；深度封包檢查用Network Firewall。",
    ),
    "Network ACLs": P(
        "在subnet邊界提供stateless、ordered allow/deny規則。",
        "入站與出站分開評估，依rule number由小到大首個匹配生效；回程ephemeral ports需明確允許。",
        "rule number、protocol、port range、CIDR、ALLOW/DENY與ephemeral return ranges。",
        "需要粗粒度subnet guardrail、封鎖特定CIDR或補充SG時。",
        "workload-to-workload身份規則優先SG；L7威脅或stateful inspection使用WAF/Network Firewall。",
    ),
    "VPC Peering": P(
        "讓兩個VPC透過私有IP直接routing。",
        "建立一對一non-transitive連線，雙方route table與SG/DNS需分別設定。",
        "acceptance、routes、DNS resolution、SG references與non-overlapping CIDRs。",
        "少量VPC、簡單全網路互通且不需要中央轉送時。",
        "VPC數量多或需transitive hub/inspection時使用Transit Gateway；只暴露服務用PrivateLink。",
    ),
    "AWS Transit Gateway": P(
        "以regional hub連接大量VPC、VPN與Direct Connect。",
        "Attachments關聯一張TGW route table並可向其他表propagate，藉此建立segmentation與transitive routing。",
        "attachments、association、propagation、TGW route tables、appliance mode、ECMP與multicast。",
        "數十到數千網路、hub-and-spoke、集中egress/inspection或hybrid routing。",
        "只有少數VPC可用Peering省每GB處理費；單一服務發佈用PrivateLink。",
    ),
    "Amazon Route 53": P(
        "提供authoritative DNS、health check與多種流量政策。",
        "Hosted zone保存records；resolver遞迴解析；routing policy在DNS回答階段選record，不代理application traffic。",
        "public/private hosted zone、alias、TTL、weighted/latency/failover/geolocation/multivalue與health checks。",
        "名稱解析、regional failover、逐步流量切換與全球endpoint selection。",
        "需要packet-level static IP加速用Global Accelerator；需要HTTP cache/proxy用CloudFront。",
    ),
    "Route 53 Resolver": P(
        "在VPC DNS與on-premises DNS之間轉送查詢。",
        "Inbound endpoint讓外部查VPC names；outbound endpoint依resolver rules把指定domain送到外部DNS。",
        "inbound/outbound endpoints、target IPs、forward/system rules、RAM sharing、query logging與SG。",
        "hybrid DNS、split-horizon與多帳號central DNS。",
        "Internet public DNS delegation使用hosted zones/NS records，不需Resolver endpoints。",
    ),
    "Elastic Load Balancing": P(
        "將連線或request分散到健康targets並隔離client與backend生命週期。",
        "Listener接收流量，rule選target group，health check移除不健康targets；型別決定可見protocol層。",
        "scheme、listeners、target groups、health checks、cross-zone、deregistration delay與idle timeout。",
        "多instance/task高可用入口與rolling deployment。",
        "全球跨Region選Route 53/Global Accelerator；API治理選API Gateway。",
    ),
    "Application Load Balancer": P(
        "提供HTTP/HTTPS Layer 7 routing與web workload入口。",
        "終止HTTP/TLS，依host/path/header/method/query routing到target groups，支援WAF與OIDC。",
        "listeners/certificates、rules priority、target type、health path、stickiness、idle timeout與access logs。",
        "網站、microservices、ECS dynamic ports、gRPC或需要content-based routing。",
        "極低延遲TCP/UDP、static IP或保留source IP需求用NLB。",
    ),
    "Network Load Balancer": P(
        "提供高吞吐、低延遲Layer 4 TCP/UDP/TLS load balancing與static IP。",
        "以flow hash選target，通常保留client source IP；可在listener做TLS termination。",
        "TCP/UDP/TLS listeners、IP/instance/ALB target、cross-zone、proxy protocol、preserve client IP與health check。",
        "非HTTP protocol、突然高連線量、static EIP或PrivateLink provider。",
        "需要path/host routing、WAF或HTTP redirect時選ALB；virtual appliances用GWLB。",
    ),
    "Gateway Load Balancer": P(
        "透明插入並擴展第三方firewall、IDS/IPS等virtual appliances。",
        "GENEVE封裝流量送到appliance fleet，endpoint與route確保雙向對稱路徑。",
        "GENEVE 6081、GWLB endpoints、route tables、target health、appliance mode與cross-zone。",
        "集中deep packet inspection且需水平擴展appliances。",
        "AWS-native stateful rules可直接用Network Firewall；一般app traffic用ALB/NLB。",
    ),
    "AWS Site-to-Site VPN": P(
        "透過Internet建立加密IPsec隧道連接VPC/TGW與on-premises。",
        "每個VPN connection有兩條隧道；BGP或static routes決定path，Internet品質影響latency。",
        "customer gateway、virtual private gateway/TGW、BGP ASN、tunnel options、routes與acceleration。",
        "快速建立hybrid連線、低至中流量、DX備援或必須原生加密。",
        "需要穩定大頻寬與可預測路徑時用Direct Connect，並常保留VPN備援。",
    ),
    "AWS Direct Connect": P(
        "提供從客戶網路到AWS的專用網路connection。",
        "實體port經virtual interfaces連到VPC、public services或TGW；BGP交換routes。",
        "connection/location、hosted/dedicated、VLAN、BGP ASN、private/public/transit VIF、DX Gateway與LAG。",
        "持續大量資料、穩定latency、private path與混合企業網路。",
        "部署需數週且本身不等於加密；快速或低成本情境先用VPN，關鍵服務採雙location。",
    ),
    "AWS Network Firewall": P(
        "在VPC中提供managed stateful/stateless L3–L7 network inspection。",
        "Firewall endpoints部署到inspection subnets，route強制流量對稱經過；stateful rules可用Suricata語法。",
        "firewall policy、stateless/stateful rule groups、HOME_NET、TLS inspection、logging與route symmetry。",
        "集中egress/ingress inspection、domain/IP filtering、IDS/IPS與合規。",
        "只需ENI allow-list用SG；HTTP application attacks用WAF；第三方appliance用GWLB。",
    ),
    "IAM": P(
        "定義AWS API的principal、authentication與authorization。",
        "Request帶principal與context；IAM彙整identity/resource/organization/session等policy後產生Allow或Deny。",
        "users/groups/roles、managed/inline policies、MFA、access keys、credential report與Access Analyzer。",
        "所有AWS control/data plane存取；人員優先federation，workload優先role。",
        "應用程式內部細粒度授權可用Verified Permissions；網路可達性不是IAM替代品。",
    ),
    "AWS IAM Identity Center": P(
        "集中管理workforce登入多個AWS accounts與business applications。",
        "連接identity source，將permission set佈署成member account roles，使用者取得temporary sessions。",
        "identity source、permission sets、assignments、session duration、MFA、SCIM與delegated administration。",
        "企業員工、群組生命週期與多帳號SSO。",
        "consumer app身份用Cognito；machine-to-machine用IAM role/OIDC federation。",
    ),
    "AWS Directory Service": P(
        "在AWS提供managed Microsoft AD、AD Connector或Simple AD以支援domain-aware workloads。",
        "Managed AD domain controllers跨AZ部署；Connector代理到既有AD而不保存完整directory。",
        "directory type/edition、VPC/subnets、trusts、DNS IPs、multi-Region replication與shared directories。",
        "Windows authentication、FSx/RDS/WorkSpaces domain integration與AD trusts。",
        "單純AWS workforce SSO優先IAM Identity Center；consumer identity用Cognito。",
    ),
    "AWS STS": P(
        "簽發有限時效的temporary AWS credentials。",
        "AssumeRole驗證trust policy與request conditions，再依role permissions和session policy產生session。",
        "role ARN、session name、duration、external ID、source identity、session tags與session policy。",
        "cross-account、federation、workload identity與避免長期access keys。",
        "不是權限資料庫；真正可做的action仍由IAM/resource policies與guardrails決定。",
    ),
    "IAM policies": P(
        "用JSON描述Effect、Action、Resource與Condition，控制principal可做什麼。",
        "Statements先匹配action/resource/principal/context；implicit deny為預設，任何applicable explicit deny勝出。",
        "Version、Statement、Sid、Effect、Action/NotAction、Resource/NotResource、Principal與Condition。",
        "可用明確ARN與conditions表達least privilege時。",
        "需要把「誰可存取」附在S3/KMS/SQS等資源上時使用resource policy。",
    ),
    "IAM roles": P(
        "提供可被人、workload或AWS service扮演的identity，沒有長期credentials。",
        "Trust policy控制sts:AssumeRole的principal；permissions policies控制session可呼叫的AWS actions。",
        "trust policy、max session duration、permissions、permissions boundary、tags與instance/task execution integration。",
        "EC2/Lambda/ECS workload、cross-account、federated user與第三方delegate。",
        "固定人員管理應使用Identity Center；不要用shared IAM user模擬role。",
    ),
    "Service control policies": P(
        "在Organizations中設定member account principals的最大權限邊界。",
        "SCP與identity/resource allow形成交集；它不授權，explicit deny可阻止member account root。",
        "target root/OU/account、Allow-list或Deny-list strategy、conditions、NotAction與policy inheritance。",
        "禁止離開核准Region、關閉audit、使用未核准服務等organization guardrails。",
        "應用角色的日常權限用IAM；資源對外access的中央邊界可用RCP。",
    ),
    "Permissions boundaries": P(
        "限制單一IAM user/role可被identity policies授予的最大權限。",
        "Effective identity permissions是identity allow與boundary allow的交集，且仍受SCP與explicit deny。",
        "managed policy ARN、iam:PermissionsBoundary creation condition與防止移除boundary的guardrail。",
        "平台委派團隊建立roles，但不允許超出安全上限。",
        "跨全組織限制用SCP；對資源本身授權用resource policy。",
    ),
    "Resource policies": P(
        "把授權規則附在S3 bucket、KMS key、SQS queue等資源上並指定Principal。",
        "資源收到request時同時評估policy；cross-account通常需要target resource allow和source identity allow。",
        "Principal、Action、Resource、Condition、organization/account/service principal與explicit Deny。",
        "cross-account、service delivery、centralized resource ownership或resource-level data perimeter。",
        "只管理一組role/user可做什麼時以identity policy較易重用。",
    ),
    "AWS KMS": P(
        "管理加密keys與授權，提供encrypt/decrypt/data-key API與audit。",
        "Envelope encryption用KMS key保護data key；大量資料由data key在service/client端加密。",
        "key policy、grants、aliases、rotation、multi-Region keys、encryption context與key spec/usage。",
        "S3/EBS/RDS等managed encryption、集中撤權、CloudTrail key-use audit。",
        "需要單租戶HSM管理、PKCS#11或更直接key control時用CloudHSM。",
    ),
    "AWS CloudHSM": P(
        "提供customer-managed、single-tenant HSM cluster與標準crypto介面。",
        "HSM跨AZ組cluster，客戶管理users、keys、backup與application integration；AWS管理硬體。",
        "cluster/subnets、HSM users、key replication、client configuration、backup與quorum。",
        "法規要求專用HSM、PKCS#11/JCE/CNG或自管key material。",
        "多數AWS服務原生加密與較低營運負擔選KMS。",
    ),
    "AWS Secrets Manager": P(
        "安全保存secret並支援版本、fine-grained access與自動rotation。",
        "Secret有AWSCURRENT/AWSPREVIOUS等version stages；rotation workflow建立、測試並切換新值。",
        "KMS key、resource policy、rotation Lambda/managed rotation、schedule、replica Regions與cache。",
        "database password、API key或需自動rotation與cross-account policy的secret。",
        "一般非敏感設定或較便宜SecureString可用Parameter Store；certificate生命週期用ACM。",
    ),
    "AWS Systems Manager Parameter Store": P(
        "階層化保存configuration與SecureString，整合IAM/KMS。",
        "Application按name/version讀取parameter；SecureString透過KMS解密，沒有Secrets Manager完整rotation workflow。",
        "String/StringList/SecureString、hierarchy、standard/advanced tier、policies、KMS key與version。",
        "feature/config values、較簡單secret、與Systems Manager automation整合。",
        "需要managed rotation、secret replicas或database integration時用Secrets Manager。",
    ),
    "AWS Certificate Manager": P(
        "申請、保存並自動更新可供整合服務使用的TLS certificates。",
        "DNS/email validation證明domain ownership；ACM-managed certificate在支援服務上自動續期。",
        "domain/SAN、validation method、key algorithm、exportability、Region與ALB/CloudFront association。",
        "ALB、CloudFront、API Gateway等TLS termination。",
        "需要在EC2自行取private key、特殊CA或device identity時評估Private CA/自管certificate。",
    ),
    "AWS WAF": P(
        "檢查HTTP(S) request並依L7規則allow、block、count、CAPTCHA或challenge。",
        "Web ACL按priority評估managed/custom rules；可看IP、header、URI、body與rate。",
        "scope、associated resource、managed rule groups、rate-based rules、IP sets、labels、logging與oversize handling。",
        "SQL injection、XSS、bots、HTTP flood、geo/IP限制與virtual patch。",
        "L3/L4 DDoS使用Shield；任意VPC packet inspection用Network Firewall。",
    ),
    "AWS Shield": P(
        "保護AWS edge與regional resources免受DDoS。",
        "Standard自動緩解常見L3/L4攻擊；Advanced增加SRT、visibility、health-based detection與cost protection。",
        "protected resources、Route 53 health checks、proactive engagement、DRT/SRT contacts與WAF integration。",
        "公開的CloudFront、Route53、Global Accelerator、ELB或EIP面臨DDoS風險。",
        "application payload攻擊仍需WAF；private east-west inspection不由Shield處理。",
    ),
    "AWS Firewall Manager": P(
        "跨Organizations accounts集中部署與稽核WAF、Shield、SG、Network Firewall等policy。",
        "Delegated admin定義policy與scope，服務持續發現資源並套用或報告noncompliance。",
        "admin account、organization scope、resource tags/types、remediation與policy type。",
        "多帳號需要一致security controls與自動套用新資源。",
        "單一帳號少量資源直接設定各服務即可；它不是封包處理data plane。",
    ),
    "Amazon GuardDuty": P(
        "從AWS telemetry偵測credential compromise、惡意活動與異常行為。",
        "Managed detectors分析CloudTrail、VPC Flow/DNS、EKS、S3、runtime等signals並產生findings。",
        "detector、protection plans、trusted IP/threat lists、publishing frequency、organization admin與EventBridge response。",
        "需要managed threat detection與多帳號集中findings。",
        "漏洞掃描用Inspector；敏感S3資料發現用Macie；調查關聯用Detective。",
    ),
    "Amazon Inspector": P(
        "持續掃描EC2、container images與Lambda packages的漏洞與暴露。",
        "比對software inventory/CVEs並結合network reachability與exploitability產生risk findings。",
        "scan types、ECR rescan duration、suppression rules、organization admin與EventBridge/Security Hub integration。",
        "patch prioritization、image pipeline與runtime workload vulnerability management。",
        "可疑行為不是漏洞時用GuardDuty；設定合規用Config。",
    ),
    "Amazon Macie": P(
        "發現、分類與保護S3中的敏感資料。",
        "先建立bucket inventory與security posture，再以managed/custom identifiers抽樣或job掃描objects。",
        "automated discovery、classification jobs、sampling、custom data identifiers、allow lists與organization admin。",
        "PII、financial、credential data盤點與S3 exposure風險。",
        "一般threat detection用GuardDuty；跨服務data catalog/governance用Glue/Lake Formation。",
    ),
    "Amazon Detective": P(
        "把security findings相關的entities與時間行為關聯，協助根因調查。",
        "建立behavior graph，彙整CloudTrail、VPC Flow、GuardDuty/EKS等資料供pivot與timeline分析。",
        "behavior graph、member accounts、data sources、finding groups與investigation scope。",
        "GuardDuty finding後追查user、role、IP、instance與activity關係。",
        "它不主動阻擋或修補；response需EventBridge、SOAR、SSM等。",
    ),
    "AWS Security Hub": P(
        "集中標準化security findings並執行security standards checks。",
        "從整合服務與partner接收ASFF findings，聚合、關聯、抑制並以automation rules分流。",
        "standards/controls、central configuration、aggregator Region、automation rules與EventBridge。",
        "SOC需要跨帳號單一finding queue與compliance view。",
        "它不取代GuardDuty/Inspector/Macie的偵測引擎，也不等於SIEM的完整log search。",
    ),
    "Amazon S3": P(
        "以HTTP API保存object，提供高durability、彈性namespace與多種storage classes。",
        "Bucket位於Region；key定位object，prefix是名稱慣例而非真正directory；PUT取代整個object。",
        "bucket type、Object Ownership、Block Public Access、bucket policy、default encryption、versioning、lifecycle與replication。",
        "static assets、backup、logs、data lake、media與write-once/read-many資料。",
        "需要block device/in-place writes選EBS；共享POSIX/NFS語意選EFS/FSx。",
    ),
    "Amazon S3 Object Lock": P(
        "在versioned S3 bucket上提供WORM retention與legal hold。",
        "Retention附在object version；governance可由具特權者繞過，compliance期限內連root也不能刪除。",
        "Object Lock enablement、versioning、governance/compliance mode、retain-until date、legal hold與bypass permission。",
        "法規保存、勒索軟體保護與不可變audit records。",
        "一般誤刪復原只需versioning/backup；compliance mode一旦設定錯誤可能無法撤回。",
    ),
    "AWS Artifact": P(
        "下載AWS合規報告與管理特定agreements。",
        "提供AWS側SOC、ISO、PCI等auditor reports；不掃描customer resources。",
        "report type、agreement、account/organization acceptance與IAM access。",
        "稽核需要AWS基礎設施證據或合約文件。",
        "customer controls與resource evidence使用Audit Manager、Config、CloudTrail。",
    ),
    "AWS Audit Manager": P(
        "持續收集AWS使用證據並對照control framework組織assessment。",
        "Framework controls映射Config、CloudTrail、Security Hub等evidence sources，產生assessment reports。",
        "framework、assessment scope、evidence sources、delegation、report destination與organization integration。",
        "PCI/HIPAA/SOC等customer-side audit preparation與evidence automation。",
        "它不自動讓resource合規；preventive controls仍需IAM/SCP/Config remediation。",
    ),
    "S3 Block Public Access": P(
        "在account、bucket或access point層阻止policy/ACL造成public access。",
        "四個flags在授權前套用最嚴格組合，可拒絕public ACL/policy或忽略既有public ACL。",
        "BlockPublicAcls、IgnorePublicAcls、BlockPublicPolicy、RestrictPublicBuckets。",
        "除非有明確public S3 use case，應在account與bucket層保持全部開啟。",
        "公開網站通常改用private S3 + CloudFront OAC，而不是關閉整體保護。",
    ),
    "S3 bucket policies": P(
        "在bucket資源側指定誰可對bucket/objects執行哪些S3 actions及條件。",
        "Policy statement匹配Principal、Action、Resource與Condition；explicit Deny可強制TLS、KMS或organization boundary。",
        "Principal、s3:ListBucket bucket ARN、object actions的/* ARN、aws:SecureTransport、aws:PrincipalOrgID與aws:SourceVpce。",
        "cross-account、CloudFront/service delivery、集中強制安全條件或整個bucket規則。",
        "只管理一個role在多項AWS服務的權限時用IAM identity policy；大量team入口可用Access Points。",
    ),
    "S3 Lifecycle": P(
        "依object age、prefix/tag與version狀態自動transition或expire資料。",
        "S3非同步套用rules；storage class有minimum duration、minimum billable size與retrieval特性。",
        "Filter、Transitions、Expiration、NoncurrentVersionTransitions、AbortIncompleteMultipartUpload與status。",
        "存取頻率可預測、需要archive、清理舊versions或未完成multipart uploads。",
        "存取模式未知時可用Intelligent-Tiering，但仍要處理archive retrieval與monitoring費。",
    ),
    "S3 Glacier": P(
        "提供S3內低成本archive storage classes，以較高取回延遲換成本。",
        "Objects仍由S3 API管理；Flexible Retrieval/Deep Archive需先restore臨時副本。",
        "Instant/Flexible/Deep Archive class、retrieval tier、restore days、minimum duration與lifecycle transition。",
        "長期備份、合規archive與極少存取資料。",
        "需要即時頻繁讀取用Standard/IA；RTO小於restore時間時不能選Deep Archive。",
    ),
    "Amazon EBS": P(
        "為EC2提供單AZ持久block volumes。",
        "Volume經network附加為block device，可format成filesystem；snapshot增量保存在regional service。",
        "gp3/io2/st1/sc1 type、size、IOPS、throughput、AZ、encryption、delete-on-termination與Multi-Attach。",
        "boot disk、database、低延遲random I/O與需要in-place update的單instance state。",
        "多AZ共享file用EFS/FSx；object/data lake用S3；temporary最高local I/O可用instance store。",
    ),
    "Amazon EFS": P(
        "提供regional或One Zone、彈性容量的managed NFS file system。",
        "各AZ mount target接收NFSv4.1；多clients共享目錄與POSIX metadata。",
        "Standard/One Zone、performance mode、throughput mode、mount targets、access points、lifecycle與TLS mount。",
        "Linux shared content、home directories、ECS/EKS/Lambda共享files。",
        "Windows SMB選FSx Windows；HPC parallel I/O選FSx Lustre；block database選EBS。",
    ),
    "Amazon FSx": P(
        "提供Windows、Lustre、NetApp ONTAP與OpenZFS等managed file systems。",
        "每種engine保留原生protocol與features，由AWS管理server、storage與backup。",
        "file-system type、deployment type、throughput capacity、storage type、AD、subnets與backup。",
        "既有應用需要SMB/AD、Lustre HPC、ONTAP多protocol或OpenZFS semantics。",
        "一般Linux NFS共享用EFS較簡單；object workload用S3。",
    ),
    "Amazon RDS": P(
        "代管關聯式database engine的provisioning、patch、backup與failover。",
        "DB instance執行engine；storage與backup由服務管理；Multi-AZ/read replica分別解決HA與read scale。",
        "engine/version、instance/storage、Multi-AZ、backup retention、maintenance window、parameter/option group、encryption與network。",
        "需要SQL transaction、joins、schema與managed operations。",
        "極高key-value scale選DynamoDB；warehouse analytics選Redshift；OS/engine深度控制用EC2。",
    ),
    "RDS Multi-AZ": P(
        "讓RDS在AZ故障時自動failover以提高availability。",
        "傳統deployment同步複寫到standby；同一DNS endpoint在failover後指向新primary。",
        "Multi-AZ deployment/cluster、failover testing、maintenance、DNS TTL與application reconnect。",
        "production database需要HA、patch期間較小中斷與AZ resilience。",
        "它不是read scaling；讀取容量用read replica/Aurora replicas。",
    ),
    "RDS read replicas": P(
        "以非同步replica增加read capacity，並可支援跨Region read/DR。",
        "Primary log changes非同步傳到replica；application必須使用獨立read endpoint並接受lag。",
        "replica count/class/Region、public accessibility、promotion、backup與replica lag alarms。",
        "read-heavy報表、全球read或可接受非同步RPO的DR。",
        "需要自動同步HA選Multi-AZ；不能把lagging replica當authoritative read。",
    ),
    "Amazon RDS Proxy": P(
        "池化與重用database connections，保護RDS/Aurora免受短暫connection storm。",
        "Proxy在client與DB間multiplex connections，使用Secrets Manager/IAM auth並感知failover。",
        "target group、Secrets Manager auth、IAM auth、max connections、idle timeout、subnets與SG。",
        "Lambda/serverless高concurrency、頻繁開關connection與需要更快failover reconnect。",
        "它不cache query也不增加DB compute；讀壓力需replica/cache或schema/index改善。",
    ),
    "Amazon Aurora": P(
        "提供MySQL/PostgreSQL-compatible relational database與分散式shared storage。",
        "Writer與readers共享跨AZ六份storage copies；compute故障不需重建整份volume。",
        "cluster/instance endpoints、replica count、I/O-Optimized、backup、failover priority、parameter groups與Global Database。",
        "需要高availability、較多read replicas、快速failover或AWS-native relational features。",
        "標準RDS有更多engine選擇且可能更便宜；NoSQL access pattern選DynamoDB。",
    ),
    "Aurora Global Database": P(
        "將Aurora cluster非同步複寫到其他Regions，提供低延遲全球讀與regional DR。",
        "Primary storage changes透過dedicated replication傳到secondary clusters；planned switchover可維持較安全切換。",
        "primary/secondary Regions、write forwarding、global write、switchover/failover、RPO monitoring與headless secondary。",
        "全球relational reads與分鐘級Region recovery。",
        "需要真正multi-active writes時需重新設計conflict semantics，或考慮DynamoDB Global Tables。",
    ),
    "Aurora Serverless": P(
        "讓Aurora compute capacity依負載在設定範圍內細粒度調整。",
        "Serverless v2以ACU擴縮cluster instances，storage仍是Aurora distributed storage。",
        "min/max ACU、auto-pause能力依版本、promotion tier、scaling configuration與RDS Proxy相容性。",
        "不可預測、間歇或多tenant database且仍需要relational semantics。",
        "穩定高負載provisioned Aurora可能更可預測/便宜；不是零connection管理。",
    ),
    "Amazon DynamoDB": P(
        "提供managed key-value/document database與單位毫秒scale。",
        "Partition key hash決定physical partition；sort key維持同partition內排序；capacity與hot key受distribution影響。",
        "PK/SK、on-demand/provisioned、RCU/WCU、GSI/LSI、consistency、TTL、Streams、PITR與transactions。",
        "已知key-based access patterns、極高scale、serverless與低營運需求。",
        "ad hoc joins/複雜transaction/reporting優先relational；不要用Scan補救錯誤key design。",
    ),
    "DynamoDB global secondary indexes": P(
        "為base table提供另一組partition/sort key的查詢入口。",
        "GSI維護獨立partition與capacity，base table更新非同步投影到index。",
        "index PK/SK、projection、capacity mode、sparse index與backfill monitoring。",
        "需要依非primary key attributes高效Query，且可接受eventual propagation。",
        "強一致GSI read不支援；需要同partition另一排序可評估LSI但須建表時定義。",
    ),
    "DAX": P(
        "為DynamoDB提供API-compatible、in-memory read-through cache。",
        "Client先查DAX cluster；miss由DAX讀DynamoDB並cache，主要加速eventually consistent reads。",
        "cluster nodes/subnets/SG、IAM、TTL、parameter group、encryption與client endpoint。",
        "microsecond級重複DynamoDB讀、read-heavy且可接受cache semantics。",
        "強一致read、複雜Redis structures或非DynamoDB資料使用ElastiCache/application cache。",
    ),
    "DynamoDB Global Tables": P(
        "把DynamoDB table複寫成multi-Region active-active。",
        "MREC模式讓每個replica local read/write並非同步複寫，以last-writer-wins收斂；MRSC模式在支援的固定三Region sets中提供multi-Region strongly consistent reads，且仍需遵守其transaction、TTL與Region限制。",
        "consistency mode（MREC/MRSC）、replica Regions、capacity、PITR、KMS、Streams、MRSC Region-set availability與application conflict assumptions。",
        "需要全球低延遲key-value access與regional resilience；若不能接受conflict，先確認workload與Region是否符合MRSC限制。",
        "跨item／跨Region複雜transaction、需要完整關聯SQL，或MRSC限制不合時，改用單writer、Aurora/DSQL或重新設計business invariant。",
    ),
    "Amazon ElastiCache": P(
        "提供managed Valkey/Redis OSS/Memcached記憶體data store。",
        "Application顯式實作cache-aside/write-through；cluster以shards/replicas擴展並依TTL/eviction清理。",
        "engine、node/serverless、cluster mode、replicas/Multi-AZ、TTL、eviction、subnets/SG與encryption。",
        "session、hot reads、leaderboard、rate limiting與降低database load。",
        "需要authoritative durability不能只放cache；DynamoDB專用API cache可用DAX。",
    ),
    "Amazon Redshift": P(
        "提供columnar MPP data warehouse供大型分析與BI。",
        "Leader規劃query，compute slices平行scan columnar blocks；distribution/sort影響shuffle與pruning。",
        "provisioned/serverless、node/RPU、distribution style/key、sort key、WLM、Spectrum與materialized views。",
        "重複BI、複雜joins、結構化warehouse與高併發dashboard。",
        "偶發直接查S3用Athena；transactional OLTP用RDS/Aurora。",
    ),
    "Amazon OpenSearch Service": P(
        "提供managed search、log analytics與vector/search indexes。",
        "Documents被分析並寫入shards；replicas提供read/availability，cluster manager維護metadata。",
        "domain/serverless collection、instance/shards/replicas、EBS、VPC access、fine-grained access、snapshots與index lifecycle。",
        "全文搜尋、可觀測性logs、near-real-time aggregations與部分vector search。",
        "不能當所有交易的唯一system of record；primary data仍放RDS/DynamoDB/S3等。",
    ),
    "Amazon DocumentDB": P(
        "提供MongoDB-compatible managed document database。",
        "Compute instances共享distributed cluster storage；支援MongoDB API的特定子集。",
        "instance/cluster、replicas、parameter group、indexes、backup、TLS、VPC與compatibility version。",
        "既有MongoDB-compatible document workload且想降低database operations。",
        "先驗證driver/operator/feature相容性；不是只因JSON就應選document database。",
    ),
    "Amazon Neptune": P(
        "提供managed graph database支援property graph與RDF。",
        "以vertices/edges或triples保存關係，針對多跳traversal執行Gremlin/openCypher/SPARQL。",
        "engine/version、instance/serverless、replicas、parameter groups、streams、backup與query language。",
        "fraud network、knowledge graph、identity relationships與推薦關係遍歷。",
        "一般key lookup用DynamoDB，transactional tabular data用RDS/Aurora。",
    ),
    "Amazon Timestream": P(
        "提供serverless time-series ingestion、storage tiering與SQL analytics。",
        "Records依dimensions/time寫入memory store，再依retention移到magnetic store。",
        "database/table、memory/magnetic retention、dimensions/measures、scheduled query與KMS。",
        "IoT telemetry、metrics、industrial events與時間窗口聚合。",
        "全文搜尋用OpenSearch；一般OLTP用RDS/DynamoDB。",
    ),
    "Amazon Athena": P(
        "以serverless SQL直接查詢S3資料。",
        "Query engine依Glue Catalog schema讀取objects；按掃描bytes計費，partition/columnar format決定成本。",
        "workgroup、output location、Glue table、partition projection、Parquet/ORC、compression與result reuse。",
        "ad hoc data lake查詢、log investigation與低營運分析。",
        "持續高頻warehouse workload用Redshift；ETL transformation由Glue/EMR。",
    ),
    "AWS Glue": P(
        "提供Data Catalog、crawler與serverless ETL/integration jobs。",
        "Crawler推斷S3/JDBC schema寫入Catalog；Spark/Ray/Python jobs讀取、轉換與寫出資料。",
        "crawler targets/classifiers、Catalog database/table、job worker type、bookmark、connection與schedule。",
        "建立共享catalog、batch ETL、schema discovery與資料品質。",
        "只是SQL查詢用Athena；需要完整Spark cluster tuning可選EMR。",
    ),
    "AWS Lake Formation": P(
        "在S3 data lake上集中管理資料註冊、table/column/row權限與跨帳號分享。",
        "以Glue Catalog metadata和LF permissions攔截整合服務存取，可使用LF-tags做ABAC。",
        "data lake locations、administrators、LF-Tags、grants、hybrid access mode與cross-account sharing。",
        "多團隊analytics需要細粒度資料治理而非大量S3 policy。",
        "一般object-level app access仍用IAM/S3 policies/Access Points。",
    ),
    "Amazon Kinesis Data Streams": P(
        "保存可重播、按partition key排序的即時event log。",
        "Hash partition key把records分到shards；每個shard內有sequence order，多consumer各自checkpoint。",
        "on-demand/provisioned mode、shards、retention、partition key、enhanced fan-out、KMS與iterator age。",
        "多個獨立consumer、需要replay、per-key ordering與AWS-native streaming。",
        "單一work queue用SQS；只需delivery到S3/Redshift用Data Firehose；Kafka ecosystem用MSK。",
    ),
    "Amazon MSK": P(
        "提供managed Apache Kafka brokers與control plane。",
        "Topics分partitions並複寫到brokers；consumer groups分攤partitions，保留Kafka protocol/ecosystem。",
        "provisioned/serverless、broker type/count、storage、partitions/replication、authentication、configuration與connectors。",
        "既有Kafka clients、portable ecosystem、長retention與複雜stream processing。",
        "不需要Kafka營運/相容性時Kinesis較AWS-native；simple queue選SQS。",
    ),
    "Amazon Data Firehose": P(
        "把streaming records以managed buffering、可選transform後送到S3/Redshift/OpenSearch等destination。",
        "Service依buffer size/time成批，呼叫Lambda轉換並管理retry與backup。",
        "source/destination、buffer hints、compression/format conversion、Lambda transform、retry與backup bucket。",
        "目標是可靠delivery而非自訂consumer與replay。",
        "需要多consumer、長期replay或per-key處理時用Kinesis Data Streams/MSK。",
    ),
    "Amazon SQS": P(
        "以managed queue解耦producer與consumer的時間和容量。",
        "SendMessage保存副本；ReceiveMessage暫時以visibility timeout隱藏，成功後DeleteMessage。",
        "Standard/FIFO、visibility timeout、long polling、retention、DLQ/redrive、encryption與batch size。",
        "work queue、burst buffer、retry與獨立擴展consumer。",
        "一對多push用SNS/EventBridge；可回播ordered log用Kinesis/MSK。",
    ),
    "SQS FIFO queues": P(
        "在message group內提供嚴格順序與deduplication能力。",
        "MessageGroupId定義ordering lane；deduplication ID在有限窗口內抑制重複enqueue。",
        "MessageGroupId、MessageDeduplicationId/content-based dedup、high-throughput mode與visibility。",
        "同一business entity必須有序，且可用多groups平行處理。",
        "全域單一group會限制throughput；business side effect仍需idempotency。",
    ),
    "Dead-letter queues": P(
        "隔離多次處理失敗的messages，避免poison message無限重試。",
        "Source queue以maxReceiveCount判斷移入DLQ；redrive可在修復後重送。",
        "redrive policy、maxReceiveCount、retention、redrive allow policy、alarm與replay procedure。",
        "需要保存失敗payload供診斷、修復與重播。",
        "DLQ不是終點；沒有owner、alarm與runbook只是在延後遺失。",
    ),
    "Amazon SNS": P(
        "以topic把同一message推送到多個subscribers。",
        "Publish後SNS fan-out到SQS、Lambda、HTTP、email/SMS等endpoint，可用filter policy。",
        "standard/FIFO topic、subscriptions、filter policy、raw delivery、DLQ、KMS與resource policy。",
        "簡單一對多通知、mobile/SMS/email或SNS→SQS fan-out。",
        "複雜event routing/archive/SaaS integration用EventBridge；pull work buffer用SQS。",
    ),
    "Amazon EventBridge": P(
        "以event bus路由AWS、SaaS與custom events到targets。",
        "Rule用JSON event pattern匹配facts並傳給targets；支援archive/replay、schema與cross-account buses。",
        "event buses、rules/patterns、targets、input transformer、archive/replay、DLQ與resource policy。",
        "domain events、cross-account integration、content-based routing與scheduler。",
        "需要durable work queue/backpressure用SQS；高吞吐replay stream用Kinesis/MSK。",
    ),
    "AWS Step Functions": P(
        "以可視化state machine編排多步驟、retry、branch、parallel與human workflow。",
        "Amazon States Language保存state transition；service integrations直接呼叫AWS APIs並記錄execution history。",
        "Standard/Express、Task/Choice/Map/Parallel/Wait、Retry/Catch、timeouts、callback token與logging。",
        "長流程、補償、人工核准、可稽核orchestration與分散式map。",
        "純event routing用EventBridge；單一背景job buffer用SQS；不要在Lambda內sleep等待。",
    ),
    "Standard Workflows": P(
        "提供durable、exactly-once workflow execution與最長一年的歷史。",
        "每個state transition持久化，可使用callback/task token等待外部或人工事件。",
        "execution timeout、history/logging、Retry/Catch、callback heartbeat與execution name。",
        "付款、order、human approval與長時間可稽核流程。",
        "極高量、短時間且可接受at-least-once/asynchronous semantics時選Express。",
    ),
    "Express Workflows": P(
        "提供高吞吐、短時間的Step Functions workflows。",
        "Optimized runtime不保存完整Standard history；sync/async Express具有不同delivery semantics。",
        "sync/async type、CloudWatch Logs、timeout、idempotency與service integration。",
        "IoT ingestion、短ETL與高TPS orchestration。",
        "長達數日、human approval或需要durable execution history時選Standard。",
    ),
    "Amazon CloudWatch": P(
        "收集metrics、logs、events與synthetic/real-user signals以監控AWS workload。",
        "AWS services送metrics；agents/apps送custom telemetry；alarms依時間窗口與statistics轉狀態。",
        "namespace/dimensions、metric resolution、statistics/percentiles、alarm periods、dashboards與retention。",
        "resource與application監控、告警、autoscaling signal與operations dashboard。",
        "API audit用CloudTrail；configuration history/compliance用Config；distributed trace用X-Ray/OTel。",
    ),
    "CloudWatch Logs": P(
        "集中保存與查詢application、service與audit logs。",
        "Log events寫入log stream/group，可用filter、Logs Insights、subscription與retention處理。",
        "log groups/streams、retention、KMS、metric/subscription filters、Logs Insights與cross-account observability。",
        "需要事件context、search、centralization與log-derived metrics。",
        "高cardinality長期archive可delivery至S3；單次request因果需tracing。",
    ),
    "CloudWatch Alarms": P(
        "將metric或composite condition轉成OK/ALARM/INSUFFICIENT_DATA並觸發action。",
        "依period、evaluation periods、datapoints-to-alarm與missing-data policy評估時間序列。",
        "metric/statistic、threshold、comparison、period、evaluation periods、M/N、treat missing data與actions。",
        "SLO symptoms、capacity、queue age、error rate與automated rollback/scaling。",
        "單一瞬時data point不應直接page；複雜business logic可先發custom metric。",
    ),
    "AWS X-Ray": P(
        "收集distributed traces並建立service map、latency與error因果。",
        "Trace由segments/subsegments組成，context跨服務傳遞；sampling控制成本。",
        "sampling rules、daemon/SDK/ADOT、annotations/metadata、groups與trace map。",
        "定位跨Lambda/API/DB request的p99 bottleneck與errors。",
        "總體趨勢先看metrics、詳細事件看logs；新instrumentation可優先OpenTelemetry。",
    ),
    "AWS Config": P(
        "記錄AWS resource configuration history並評估rules/conformance packs。",
        "Configuration recorder擷取changes，rules在變更或週期時評估COMPLIANT/NON_COMPLIANT。",
        "recorder、delivery channel、managed/custom rules、conformance packs、aggregator與remediation。",
        "回答「資源何時變成這樣」、組態合規與多帳號inventory。",
        "回答「誰呼叫API」用CloudTrail；runtime health用CloudWatch。",
    ),
    "AWS CloudTrail": P(
        "記錄AWS API與account activity供audit與調查。",
        "Management events預設進event history；trail/event data store可保存management/data/insight events。",
        "multi-Region/organization trail、management/data events、S3/KMS、log validation、CloudWatch integration與Lake。",
        "追查who/what/when/source IP、不可否認audit與security detection。",
        "application log與performance metric不是CloudTrail用途。",
    ),
    "AWS CloudFormation": P(
        "以declarative templates建立、更新與刪除AWS resources。",
        "CloudFormation建立dependency graph並呼叫service APIs；stack state與events支援rollback。",
        "Parameters、Mappings、Resources、Outputs、Conditions、DependsOn、DeletionPolicy、UpdateReplacePolicy與stack policy。",
        "repeatable environment、reviewable IaC與cross-account StackSets。",
        "需要一般程式語言抽象可用CDK產生templates；runtime config用AppConfig/Parameter Store。",
    ),
    "CloudFormation change sets": P(
        "在執行stack update前預覽將新增、修改、替換或刪除的resources。",
        "CloudFormation比較template/parameters與現有stack，產生proposed changes但不保證外部副作用。",
        "change set type、include nested stacks、replacement、capabilities與execution。",
        "production IaC review、辨識replacement與降低誤刪風險。",
        "仍需policy-as-code、tests與rollback；change set不能偵測所有service runtime impact。",
    ),
    "AWS CloudFormation StackSets": P(
        "把相同CloudFormation stack部署到多帳號、多Regions。",
        "Service-managed模式整合Organizations並自動部署到OU accounts；operations控制並行與failure tolerance。",
        "permission model、targets OU/accounts、Regions、auto-deployment、concurrency與failure tolerance。",
        "organization-wide baseline、roles、Config rules、logging resources。",
        "帳號供應完整landing zone使用Control Tower/Account Factory；app單帳號stack不需StackSets。",
    ),
    "AWS CodeDeploy": P(
        "協調EC2/on-premises、Lambda與ECS application deployments。",
        "Deployment group依strategy轉移traffic並執行lifecycle hooks；health/alarm可觸發rollback。",
        "compute platform、deployment group、blue/green/in-place、traffic shifting、AppSpec、hooks與alarms。",
        "需要managed rolling/blue-green、Lambda aliases或ECS task set切流。",
        "完整CI/CD orchestration需CodePipeline或外部pipeline；IaC資源由CloudFormation。",
    ),
    "AWS Systems Manager": P(
        "集中管理EC2與hybrid managed nodes的inventory、run commands、patch與automation。",
        "SSM Agent透過IAM與service endpoints輪詢control plane，通常不需開inbound SSH。",
        "managed instance role、VPC endpoints、documents、associations、inventory、maintenance windows與automation。",
        "fleet operations、patch、secure access、runbook與remediation。",
        "container orchestration用ECS/EKS；純configuration storage是Parameter Store子功能。",
    ),
    "Session Manager": P(
        "透過Systems Manager建立可稽核shell/port-forwarding，不需bastion或inbound SSH。",
        "Authenticated user經SSM control channels連到agent；session traffic可加密並記錄。",
        "instance role、agent/endpoints、session preferences、KMS、S3/Logs logging與IAM conditions。",
        "private instances的administrative access、減少SSH keys與public IP。",
        "若agent或SSM endpoint不可用需break-glass path；它不是application user access。",
    ),
    "Patch Manager": P(
        "依baseline與maintenance windows掃描/安裝managed nodes patches。",
        "SSM Agent執行patch document，依OS repository與baseline分類approved/rejected。",
        "patch baseline、approval delay、patch groups、maintenance window、scan/install與compliance reporting。",
        "EC2/hybrid OS fleet規模化patch與audit。",
        "immutable image workflow可用Image Builder+rolling replacement，避免in-place drift。",
    ),
    "AWS Fault Injection Service": P(
        "以受控實驗注入AWS resource failures驗證resilience。",
        "Experiment template選targets/actions/stop conditions，service role執行故障並由CloudWatch alarm中止。",
        "targets/tags、actions、duration、stop conditions、IAM role、experiment report與safety limits。",
        "game day、驗證AZ/instance/network failure、alarm與recovery automation。",
        "不能替代load test或backup restore；先縮小blast radius並設stop conditions。",
    ),
    "Savings Plans": P(
        "用一或三年每小時compute spend承諾換取折扣。",
        "帳單把eligible usage套用承諾；Compute SP較彈性，EC2 Instance SP較限定。",
        "Compute/EC2/SageMaker type、term、payment option、hourly commitment、sharing與coverage/utilization。",
        "可預測baseline compute且希望跨family/Region較彈性。",
        "特定EC2屬性與容量保留需求比較RI/Capacity Reservation；可中斷工作用Spot。",
    ),
    "Reserved Instances": P(
        "為特定EC2/RDS等使用承諾提供billing discount，某些EC2 zonal RI兼具capacity reservation。",
        "Billing依instance attributes匹配discount；Standard與Convertible交換彈性不同。",
        "scope、instance family/type、platform、tenancy、term、payment與offering class。",
        "穩定、明確的instance footprint或需要zonal capacity benefit。",
        "跨family/Region彈性通常Compute Savings Plans較佳；RI不會自動讓instance啟動。",
    ),
    "EC2 Spot Instances": P(
        "使用AWS剩餘EC2 capacity取得大幅折扣，但可能被中斷。",
        "Capacity需求變化時AWS發出短通知回收instance；價格不是唯一風險，capacity pool多樣性更重要。",
        "allocation strategy、instance diversification、capacity-optimized、max price、interruption handling與mixed instances policy。",
        "batch、stateless、queue workers、CI、HPC等可checkpoint/重試工作。",
        "不可中斷single point、stateful primary或無重試設計不能只用Spot。",
    ),
    "AWS Compute Optimizer": P(
        "根據歷史metrics與ML提出EC2/EBS/Lambda/ECS等rightsizing建議。",
        "分析CPU、memory（需agent）、network與利用率，估計性能風險與節省。",
        "opt-in、lookback、enhanced infrastructure metrics、external metrics ingestion與recommendation preferences。",
        "找over/under-provisioned resources並建立rightsizing候選。",
        "建議不是自動安全變更；需load test、seasonality、license與SLO驗證。",
    ),
    "AWS Cost Explorer": P(
        "互動分析歷史與預測成本、usage與RI/SP coverage。",
        "Billing data按service/account/tag/dimension聚合，可建立reports與anomaly investigation。",
        "date/granularity、filters/group by、cost metric、forecast、RI/SP reports與cost allocation tags。",
        "回答成本趨勢、來源、forecast與commitment coverage。",
        "逐筆最細分析與自訂BI使用CUR/Data Exports；預算guardrail用Budgets。",
    ),
    "AWS Cost and Usage Report": P(
        "輸出最細AWS billing line items到S3供查詢與chargeback。",
        "定期產生含resource IDs、tags、pricing與credits的files，可透過Athena/Glue/Redshift分析。",
        "report/data export、S3 bucket、time granularity、resource IDs、split cost allocation與format。",
        "FinOps、showback/chargeback、unit economics與自訂cost allocation。",
        "快速互動圖表用Cost Explorer；通知閾值用Budgets。",
    ),
    "AWS Budgets": P(
        "對cost、usage、RI/SP utilization/coverage設定threshold與通知/action。",
        "Budget依billing data週期評估actual/forecast，越過threshold觸發SNS/email或budget action。",
        "budget type/period、filters、actual/forecast thresholds、subscribers與IAM/SCP action。",
        "防止成本意外、team budget與commitment低利用率告警。",
        "它不是即時hard spending cap；真正阻止資源建立需IAM/SCP/service controls。",
    ),
    "AWS Backup": P(
        "以policy集中排程、保存與複製多種AWS resource backups。",
        "Backup plan選resources並寫recovery points到vault；copy rules可跨account/Region。",
        "backup plan/rule、schedule、lifecycle、vault/KMS、resource assignment、copy action與restore testing。",
        "多服務一致backup governance、cross-account vault與合規reporting。",
        "database-native point-in-time/replication仍有價值；backup成功不等於restore符合RTO。",
    ),
    "Backup Vault Lock": P(
        "以WORM controls防止backup recovery points在保留期內被刪除或縮短。",
        "Governance可由特權繞過；Compliance在grace period後連root也不能改。",
        "governance/compliance mode、min/max retention、changeable grace time、KMS與cross-account copy。",
        "勒索軟體隔離、法規不可變保存與security account vault。",
        "若保留規則尚未驗證先用governance；compliance設定錯誤可能無法逆轉。",
    ),
    "AWS Elastic Disaster Recovery": P(
        "把server block data持續複寫到AWS低成本staging area，故障時快速launch recovery instances。",
        "Agent傳送block changes到replication servers/EBS；launch template在drill/cutover建立target。",
        "source servers、staging subnet、replication settings、launch template、point-in-time snapshot與drill。",
        "on-premises/other cloud servers的lift-and-shift DR與低RPO。",
        "雲原生database/object workload優先native replication/backup；它不自動解決app dependency order。",
    ),
    "AWS Resilience Hub": P(
        "定義application resilience policy並評估components是否滿足RTO/RPO。",
        "匯入app resources與relationships，套policy分析故障與提出recommendations，可整合FIS/SOP。",
        "application definition、resilience policy、RTO/RPO targets、assessment、alarms/SOP/tests。",
        "portfolio resilience posture、gap analysis與持續驗證。",
        "它不替你執行所有failover；實作仍在服務配置、runbook與game day。",
    ),
    "Service Quotas": P(
        "查看與申請AWS service quotas，避免capacity在流量前先被control limit阻擋。",
        "每account/Region quota限制resource或API rate；可用CloudWatch與request workflow管理。",
        "quota code、applied/default value、automatic management、CloudWatch usage與increase request。",
        "launch readiness、multi-account capacity planning與throttling診斷。",
        "提高quota不會修復下游瓶頸或成本；仍需admission control與graceful degradation。",
    ),
    "AWS Organizations": P(
        "集中建立accounts、OU、政策與consolidated billing。",
        "Management account控制organization metadata；policies繼承到OU/accounts，各account仍是獨立security boundary。",
        "roots/OUs/accounts、SCP/RCP/tag/backup policies、delegated admins、trusted access與billing sharing。",
        "多團隊、多環境、blast-radius隔離與central governance。",
        "單一account內的日常permission仍用IAM；不要在management account執行workloads。",
    ),
    "AWS Control Tower": P(
        "建立與治理符合best practices的multi-account landing zone。",
        "在Organizations、Identity Center、Config/CloudTrail等之上佈署controls、account baseline與dashboard。",
        "landing zone Regions、OU、controls、Account Factory/AFT、log archive、audit account與drift repair。",
        "快速建立一致account vending與preventive/detective/proactive controls。",
        "高度自訂既有Organizations可能需漸進enrollment；Control Tower不是新型hypervisor。",
    ),
    "AWS Account Factory": P(
        "以Control Tower核准blueprint自助供應新AWS accounts。",
        "透過Service Catalog/AFT pipeline收集account metadata並套landing-zone baseline。",
        "account email/name、OU、SSO owner、network blueprint、AFT customizations與lifecycle events。",
        "大量team/project accounts且需要一致guardrails與審批。",
        "不要用單一共享account加tags取代真正blast-radius與billing boundaries。",
    ),
    "AWS Migration Hub": P(
        "集中追蹤migration portfolio、waves與多工具進度。",
        "彙整discovery與migration tools狀態，提供application grouping與journey visibility。",
        "home Region、discovery sources、applications、waves、connectors與orchestrator templates。",
        "大型migration需要single pane追蹤而不是spreadsheet碎片。",
        "它不搬資料本身；server用MGN、database用DMS、files用DataSync。",
    ),
    "AWS Application Discovery Service": P(
        "收集on-premises server inventory、utilization、process與network dependencies。",
        "Agentless collector或agent將資料送至Migration Hub，供right-size與wave planning。",
        "agent/agentless mode、data collection、export、network connections與application grouping。",
        "migration assessment、dependency mapping與portfolio sizing。",
        "只看CMDB可能過時；但自動發現仍需business owner驗證。",
    ),
    "Migration Evaluator": P(
        "建立現有環境成本與AWS business case/TCO分析。",
        "Collector或inventory資料分析utilization、licensing與right-sizing，產生migration assessment。",
        "inventory source、utilization window、license assumptions、target Regions與cost model。",
        "需要財務批准、TCO與migration prioritization。",
        "它不是技術dependency map或實際migration engine。",
    ),
    "AWS Application Migration Service": P(
        "把physical、virtual或cloud servers以block replication搬到EC2。",
        "Agent持續複寫disk到staging area；test/cutover launch settings建立EC2。",
        "replication template、staging subnet、launch template、post-launch actions、test/cutover與lag。",
        "rehost大量servers、低downtime cutover與DR-like migration。",
        "database engine轉換用DMS/SCT；refactor/serverless需另外重新架構。",
    ),
    "AWS DMS": P(
        "在線搬移或持續複寫databases/data stores，降低downtime。",
        "Replication instance/serverless task做full load與CDC，讀source logs並寫target。",
        "source/target endpoints、replication instance/serverless、full-load/CDC task、table mappings、LOB與validation。",
        "homogeneous/heterogeneous database migration與ongoing replication。",
        "schema/code conversion使用SCT；一般files用DataSync；DMS不自動修正所有data types。",
    ),
    "AWS Schema Conversion Tool": P(
        "評估並轉換異質database schema與部分code objects。",
        "讀取source metadata，產生assessment report與target DDL；無法自動轉換項目需人工處理。",
        "source/target engine、assessment report、conversion rules、extension pack與action items。",
        "Oracle/SQL Server等轉PostgreSQL/Aurora或warehouse migration。",
        "實際資料full load/CDC用DMS；同engine migration可能不需SCT。",
    ),
    "AWS DataSync": P(
        "以managed agent高效在線搬移NFS/SMB/object data到AWS storage或跨storage。",
        "Agent平行讀寫、加密傳輸、驗證完整性並依task schedule執行。",
        "source/destination location、agent、include/exclude filters、bandwidth、verification、schedule與task report。",
        "持續或一次性online file/object migration、metadata保留與驗證。",
        "離線大規模且bandwidth不足用Snow；提供持續hybrid storage介面用Storage Gateway。",
    ),
    "AWS Storage Gateway": P(
        "在on-premises提供file/volume/tape介面，後端整合AWS storage。",
        "Virtual/hardware appliance維持local cache並把資料非同步寫入S3/EBS snapshots/virtual tape。",
        "File/Volume/Tape gateway、cache/storage disks、SMB/NFS/iSCSI、bandwidth與CloudWatch。",
        "legacy apps需維持local protocol、hybrid cache、backup/tape modernization。",
        "只要快速搬完資料用DataSync；它不是一般跨Region filesystem。",
    ),
    "AWS Transfer Family": P(
        "以managed SFTP/FTPS/FTP/AS2 endpoints把partner files存入S3/EFS。",
        "Service終止protocol與authentication，將user映射到IAM role和logical directory。",
        "protocol/endpoint type、identity provider、user role/home directory、logging、workflow與custom hostname。",
        "合作夥伴必須保留傳統file-transfer protocol而後端想用AWS storage。",
        "內部bulk migration用DataSync；不要為SFTP自行長期維護EC2 servers。",
    ),
    "AWS Snow Family": P(
        "以實體devices進行離線large-scale data transfer或edge compute。",
        "AWS寄送加密device；客戶copy後寄回，AWS匯入指定storage。",
        "job/device type、capacity、KMS、shipping、import target、cluster/edge compute與chain of custody。",
        "網路頻寬無法在migration window內搬完PB級資料。",
        "持續同步或可用足夠線路時DataSync/DX更合適；必須先確認所在Region與服務供應狀態。",
    ),
    "Amazon API Gateway": P(
        "提供managed REST/HTTP/WebSocket API入口、授權、throttling與整合。",
        "Gateway驗證request、執行authorizer/mapping，再代理Lambda、HTTP或AWS service integration。",
        "REST/HTTP/WebSocket API、routes/resources、stages、authorizers、usage plans、throttling、CORS與integration timeout。",
        "serverless API、公開/私有API、consumer治理與request transformation。",
        "一般web load balancing用ALB；長時間或非常高吞吐TCP用NLB。",
    ),
    "Amazon Cognito": P(
        "為consumer/mobile/web applications提供user sign-up/sign-in與AWS credential federation。",
        "User Pool發OIDC tokens；Identity Pool把已驗證身份交換成temporary IAM credentials。",
        "user pool、app client、hosted UI、MFA、federation、groups、identity pool roles與token lifetime。",
        "數十萬外部customers的authentication與social/enterprise federation。",
        "員工多帳號AWS console access用IAM Identity Center；service workload用IAM role。",
    ),
    "Amazon ECR": P(
        "保存、掃描與複寫OCI container images/artifacts。",
        "Registry以repository/tag/digest管理layers；ECS/EKS execution role拉取image。",
        "repository policy、lifecycle policy、immutability、scan on push、KMS與cross-Region/account replication。",
        "ECS/EKS/Fargate的private image supply chain。",
        "它不執行containers；執行由ECS/EKS/App Runner等負責。",
    ),
    "AWS Batch": P(
        "排程大量batch jobs到managed compute environments。",
        "Job進queue，由scheduler依priority/dependencies放到EC2/Spot/Fargate capacity。",
        "job definition、queue priority、compute environment、vCPU/memory/GPU、array jobs、retry與timeout。",
        "rendering、scientific、ETL與可排隊的container batch。",
        "持續service用ECS/EKS；Spark/Hadoop ecosystem用EMR。",
    ),
    "Amazon EMR": P(
        "提供managed Spark/Hadoop等big-data frameworks。",
        "Cluster或serverless runtime把資料分區到workers平行處理，常以S3為durable storage。",
        "EC2/Serverless/EKS deployment、release label、instance fleets、managed scaling、EMRFS與bootstrap。",
        "需要Spark、Hive、Presto、HBase等framework與大型ETL/ML。",
        "單純serverless SQL用Athena；managed visual ETL/catalog用Glue。",
    ),
    "AWS Elastic Beanstalk": P(
        "從application package建立並管理EC2、ASG、ELB等web環境。",
        "Platform version與configuration options產生底層CloudFormation resources並執行deployment policies。",
        "platform、environment tier、instance/ASG、LB、deployment policy、.ebextensions與saved configuration。",
        "開發團隊要快速部署傳統web app，但仍想保留底層resource控制。",
        "container-first可用ECS/App Runner；event-driven短函式用Lambda。",
    ),
    "Amazon Lightsail": P(
        "以固定月費bundle簡化小型VM、database、container與network部署。",
        "把compute、SSD、transfer與簡化控制面包成套餐，降低初學與小workload操作。",
        "blueprint/bundle、static IP、firewall、snapshot、load balancer與managed database。",
        "小網站、prototype與可預測低複雜度workload。",
        "需要完整VPC、enterprise governance、細粒度autoscaling或進階服務整合時改用EC2/ECS等。",
    ),
    "Amazon Elastic Transcoder": P(
        "將S3中的媒體檔轉換成不同codec、resolution與format。",
        "Pipeline從input bucket讀取job，依preset轉碼並寫output bucket。",
        "pipeline、input/output bucket、IAM role、preset、notifications與job。",
        "既有legacy簡單file transcoding workflow。",
        "新影音pipeline通常評估AWS Elemental MediaConvert；需確認服務目前可用性與官方建議。",
    ),
    "AWS Elemental MediaConvert": P(
        "以broadcast-grade managed file transcoding將S3中的影音source轉成多種codec、resolution與封裝格式。",
        "Application建立job並引用input/output S3 locations、job template與queue；MediaConvert讀取source、執行轉碼後寫回S3，再以EventBridge發出狀態事件。",
        "queue、job/template、input/output groups、codec、IAM service role、acceleration、priority與EventBridge notifications。",
        "新建video-on-demand workflow，需要managed file-based transcoding、ABR outputs與可觀測job狀態。",
        "Live streaming選MediaLive；簡單圖片處理可用Lambda/Batch；特殊codec或GPU控制才自建。Elastic Transcoder已於2025-11-13停止支援，不應用於新架構。",
    ),
    "AWS App Runner": P(
        "從source或container image快速提供managed web service。",
        "Service建立build/deploy與autoscaling runtime，透過public endpoint接HTTP requests。",
        "source/image、build/start command、CPU/memory、autoscaling、health check、instance role與VPC connector。",
        "小團隊快速上線stateless web/API且不想管理orchestrator。",
        "複雜network、sidecars、GPU或平台標準化需求選ECS/EKS；應確認新workload的服務可用與產品路線。",
    ),
    "Amazon Bedrock": P(
        "以managed API使用foundation models並組合RAG、agents、guardrails與evaluation。",
        "Runtime把prompt送到選定model；上層features管理retrieval、tool orchestration與safety policy。",
        "model access、inference profile、temperature/max tokens、VPC endpoint、KMS、logging與IAM。",
        "需要快速使用多家FMs、少管理training infrastructure與AWS-native GenAI building blocks。",
        "需要完整model training、custom container與深度ML control時用SageMaker。",
    ),
    "Amazon Bedrock Knowledge Bases": P(
        "managed RAG：ingest documents、建立embeddings、檢索並提供grounding context。",
        "Data source同步後chunk→embed→vector store；runtime retrieve或retrieve-and-generate。",
        "data source、chunking、embedding model、vector store、metadata filters、reranker與sync。",
        "企業文件問答與希望少建自訂RAG pipeline。",
        "需要特殊parser、retrieval algorithm或極細控制時自建Glue/Lambda/OpenSearch pipeline。",
    ),
    "Amazon Bedrock Agents": P(
        "讓FM依instruction選action groups與knowledge sources完成多步任務。",
        "Agent規劃tool calls，透過Lambda/API執行action並把observation回傳model迭代。",
        "foundation model、instruction、action groups/schema、Lambda role、knowledge base、memory與trace。",
        "有界、可稽核的tool-using assistant與workflow。",
        "deterministic高風險流程使用Step Functions；agent不應持有無界共享admin credentials。",
    ),
    "Amazon Bedrock Guardrails": P(
        "在model input/output套用content、denied topics、PII、word與grounding policies。",
        "Guardrail在inference前後分類/過濾內容，可獨立於特定model版本使用。",
        "content filters、denied topics、word filters、sensitive information、contextual grounding與version。",
        "需要一致safety policy、PII遮罩與跨model治理。",
        "它不是IAM、network isolation或事實正確性的完整替代；需多層controls/evals。",
    ),
    "Amazon Bedrock AgentCore Identity": P(
        "讓AI agents代表自身或使用者安全取得tool credentials與委派身份。",
        "以workload/user identity交換短期、scoped credentials，降低把長期secret放進agent context的風險。",
        "identity provider、workload identity、credential provider、OAuth scopes、token vault與resource policy。",
        "agent需呼叫第三方/AWS tools且要保留user delegation與audit boundary。",
        "簡單AWS service-to-service仍可用IAM role；高風險action要再加human approval。",
    ),
    "AWS AppConfig": P(
        "安全發布runtime configuration與feature flags，不需重新部署程式。",
        "Hosted/external config經validators與deployment strategy漸進推出；agent/cache讓app本地讀取。",
        "application/environment/profile、validators、deployment strategy、bake time、alarms與feature flag attributes。",
        "kill switch、dynamic limits、endpoint切換與低風險漸進配置。",
        "基礎設施desired state用CloudFormation；secret用Secrets Manager。",
    ),
    "CloudWatch Synthetics": P(
        "以排程canary從外部視角驗證URL、API與browser journey。",
        "Lambda-based canary執行script，送metrics/logs/screenshots與trace。",
        "schedule、runtime、script、environment variables、VPC、artifacts、alarms與X-Ray。",
        "在沒有真實流量時持續驗證availability、DNS/TLS/login與critical path。",
        "它不能取代真實user monitoring或backend metrics；應一起建立evidence chain。",
    ),
    "Health checks": P(
        "從AWS外部或CloudWatch alarm判斷endpoint是否健康，供Route 53 routing policy決定是否回傳該record。",
        "Route 53 health checker定期探測指定IP/domain、port與path；calculated check可組合多個checks，private endpoint通常以CloudWatch alarm間接表示健康。",
        "protocol、IP/domain、port、request path、failure threshold、measure latency、inverted、calculated children與alarm association。",
        "DNS failover、multi-value answers或需要把不健康endpoint移出DNS回答時。",
        "需要逐request代理、connection draining或target-level routing時使用load balancer health checks；DNS check不會終止既有connection。",
    ),
    "Direct Connect Gateway": P(
        "把private/transit virtual interfaces連到跨Region的VGW或Transit Gateway associations。",
        "DX gateway位於連線與VPC/TGW gateway之間，透過BGP allowed prefixes交換可達網段，但不提供VPC間任意transitive routing。",
        "gateway associations、allowed prefixes、private/transit VIF、BGP ASN、route advertisements與association proposals。",
        "同一DX連線需要觸及多個Region的VPC或TGW，並集中管理on-premises prefix交換時。",
        "單一Region單一VPC可直接使用private VIF到VGW；需要VPC間hub routing由Transit Gateway負責。",
    ),
    "Envelope encryption": P(
        "使用data key加密大量資料，再以KMS key加密data key，避免每個資料區塊都直接呼叫KMS。",
        "應用呼叫GenerateDataKey取得plaintext與encrypted data key；plaintext只在memory中使用後清除，encrypted data key與ciphertext一起保存。",
        "KMS key、encryption context、data-key algorithm、key policy、grants、rotation與ciphertext metadata。",
        "大型object、database field或client-side encryption需要兼顧效能、key audit與集中撤銷時。",
        "小型service-integrated encryption可直接使用服務SSE；envelope encryption不會取代IAM、TLS或資料分類。",
    ),
    "Amazon Machine Images": P(
        "保存EC2啟動所需的root-volume template、block-device mapping與launch permissions。",
        "啟動instance時由AMI建立root EBS snapshot-backed volume並套用architecture、boot mode與mapping；AMI本身不是正在執行的server。",
        "image ID、Region/copy、architecture、root device、block mappings、launch permissions、deprecation與Image Builder pipeline。",
        "建立immutable server baseline、Auto Scaling launch template或跨帳號核准映像時。",
        "只需部署container application時使用container image；執行中的資料與設定不應只靠AMI保存。",
    ),
    "Placement groups": P(
        "控制EC2 instances在底層硬體上的相對位置，以交換latency、failure isolation或分區拓撲。",
        "Cluster把instances靠近以降低network latency；spread分散少量instances到不同硬體；partition把大型fleet分到可見partition failure domains。",
        "strategy、partition count、instance type support、tenancy、AZ與capacity reservation。",
        "HPC低延遲、少量關鍵nodes硬體隔離，或Kafka/HDFS等partition-aware叢集。",
        "一般web fleet先跨AZ使用Auto Scaling；placement group不能提供跨Region或application-level HA。",
    ),
    "EBS snapshots": P(
        "建立EBS volume的增量、point-in-time block backup，供restore、copy與AMI使用。",
        "首份snapshot保存已寫入blocks，後續只保存變更；刪除中間snapshot不會破壞仍被後續snapshot需要的blocks。",
        "snapshot schedule、retention、KMS key、cross-account/Region copy、archive tier、Fast Snapshot Restore與Recycle Bin。",
        "volume backup、跨Region DR copy、golden AMI與誤刪恢復。",
        "需要持續低RPO複寫與快速server recovery時搭配Elastic Disaster Recovery；snapshot不等於Multi-AZ volume。",
    ),
    "AWS Auto Scaling": P(
        "以scaling plans跨多種scalable resources協調容量預測與target tracking。",
        "服務從CloudWatch demand history建立forecast並調整支援資源；實際可伸縮邊界仍由各服務的min/max與scalable target決定。",
        "scaling plan、resource selection、forecast、target utilization、min/max capacity與dynamic/predictive scaling。",
        "舊式需要跨多資源統一scaling plan的情境，或比較predictive與dynamic scaling概念時。",
        "新工作負載通常直接使用各服務的Application Auto Scaling或EC2 Auto Scaling政策，取得更完整功能。",
    ),
    "Lambda concurrency": P(
        "控制Lambda同時執行的數量，連結輸入速率、下游容量、throttling與啟動延遲。",
        "每個並行request需要execution environment；reserved concurrency同時保留並限制函式額度，provisioned concurrency預先初始化環境。",
        "account quota、reserved concurrency、provisioned concurrency、event-source maximum concurrency、batch size與throttles。",
        "保護database連線、隔離關鍵函式容量、降低可預測流量的cold-start latency。",
        "持續高利用率或超長工作改用container/EC2；提高concurrency不能修復下游容量不足。",
    ),
    "Enhanced fan-out": P(
        "讓Kinesis consumer取得每shard專用讀取throughput與較低傳遞延遲。",
        "Consumer註冊後由Kinesis以HTTP/2 push records；不同enhanced consumers不再共享傳統GetRecords的per-shard read throughput。",
        "registered consumer、SubscribeToShard、consumer ARN、shard count、read throughput、retention與consumer lag。",
        "多個低延遲consumers同讀stream且傳統shared throughput造成lag或互相競爭時。",
        "少量可接受polling latency的consumer可用shared throughput；enhanced fan-out不修復hot partition key。",
    ),
    "AWS Distro for OpenTelemetry": P(
        "以OpenTelemetry相容SDK與collector收集metrics、traces及相關telemetry並送往AWS觀測服務。",
        "Application instrumentation產生OTLP資料，collector接收、處理、取樣並export到X-Ray、CloudWatch或其他相容backend。",
        "SDK auto/manual instrumentation、collector receivers/processors/exporters、sampling、resource attributes與IAM。",
        "需要vendor-neutral instrumentation、跨ECS/EKS/EC2/Lambda統一收集pipeline時。",
        "只需要AWS managed trace backend可直接使用X-Ray SDK/daemon；telemetry仍需正確context propagation。",
    ),
    "AWS CDK": P(
        "以程式語言constructs定義AWS基礎設施，再合成CloudFormation templates部署。",
        "CDK app建立construct tree；synth產生template與assets metadata，deploy仍由CloudFormation建立change set和管理resource state。",
        "app/stacks、constructs、context、bootstrap、assets、synth、diff、permissions boundary與deployment role。",
        "團隊希望用TypeScript/Python等語言封裝重用架構construct，同時保留CloudFormation deployment model。",
        "需要直接審核純宣告template可用CloudFormation；CDK不是取代CloudFormation state engine。",
    ),
    "AWS Lambda aliases": P(
        "以穩定名稱指向特定Lambda version，並可在兩個versions之間分配呼叫權重。",
        "Alias保存primary version與可選additional version weight；CodeDeploy可逐步調整權重並由CloudWatch alarms觸發rollback。",
        "published versions、alias name、routing config、provisioned concurrency、CodeDeploy deployment config、alarms與hooks。",
        "Lambda canary/linear deployment、穩定invoke ARN與版本rollback。",
        "需要HTTP path/host routing用API Gateway/ALB；alias流量切分不會遷移外部state或schema。",
    ),
}


ALIASES = {
    "AWS VPC IP Address Manager": "AWS VPC IP Address Manager",
    "Network Load Balancer": "Network Load Balancer",
    "Application Load Balancer": "Application Load Balancer",
    "Gateway Load Balancer": "Gateway Load Balancer",
    "Lambda@Edge": "Lambda@Edge",
    "AWS Directory Service": "AWS Directory Service",
    "IAM permissions boundaries": "Permissions boundaries",
    "Amazon S3 Object Lock": "Amazon S3 Object Lock",
    "AWS Artifact": "AWS Artifact",
    "AWS Audit Manager": "AWS Audit Manager",
    "EC2 instance store": "Amazon EC2",
    "Auto Scaling": "Amazon EC2 Auto Scaling",
    "AWS Lambda reserved concurrency": "AWS Lambda",
    "AWS SDK retry behavior": "Amazon SQS",
    "Amazon SQS FIFO": "SQS FIFO queues",
    "Amazon DynamoDB Accelerator": "DAX",
    "DynamoDB Global Tables": "DynamoDB Global Tables",
    "DynamoDB Streams": "Amazon DynamoDB",
    "Amazon DynamoDB Streams": "Amazon DynamoDB",
    "Amazon Kinesis": "Amazon Kinesis Data Streams",
    "CloudWatch Logs": "CloudWatch Logs",
    "CloudWatch Alarms": "CloudWatch Alarms",
    "Reserved Instances": "Reserved Instances",
    "Amazon S3 Lifecycle": "S3 Lifecycle",
    "AWS CloudFormation StackSets": "AWS CloudFormation StackSets",
    "AWS Systems Manager": "AWS Systems Manager",
    "Session Manager": "Session Manager",
    "Patch Manager": "Patch Manager",
    "IAM ABAC": "IAM policies",
    "Amazon EC2 Auto Scaling": "Amazon EC2 Auto Scaling",
    "Amazon ECR": "Amazon ECR",
    "AWS Lambda Powertools": "AWS Lambda",
}


def component_profile(name: str, topic: Topic) -> ComponentProfile:
    canonical = ALIASES.get(name, name)
    if canonical in PROFILES:
        return PROFILES[canonical]
    if name == "Amazon EC2 Auto Scaling":
        return P(
            "依需求維持與調整EC2 fleet capacity。",
            "Launch template定義instance；group跨subnets放置；scaling policy依metric改desired capacity。",
            "min/max/desired、launch template、subnets、health check、target tracking、warmup與mixed instances。",
            "stateless EC2水平擴展、Multi-AZ replacement與可預測/動態容量。",
            "container scheduler使用ECS/EKS service scaling；單純排程開關機不等於autoscaling。",
        )
    return P(
        f"在「{topic.title}」中負責一個明確的架構責任，而不是可隨意互換的產品名稱。",
        f"它必須與本章的state、request flow及failure boundary一起看；核心決策是：{topic.decision}",
        f"至少確認scope、identity policy、network path、encryption、capacity/quota、logging與lifecycle；本章服務名稱為{name}。",
        f"當需求符合「{topic.scenario}」且它直接滿足hard constraint時使用。",
        f"若應用真正需要「{topic.alternative}」，應替換或與相鄰component組合。",
    )
