"""Topics 1–40: foundations, networking, security, and compute."""
from aws_architect_topic_factory import topic


TOPICS = [
    topic(1, "如何使用本書與雙證地圖",
          "服務名稱很多，但考試真正要求把需求轉成可辯護的架構決策。",
          "先圈出安全、可靠、效能、成本與營運限制，再比較符合限制的最小方案。",
          "從熟悉的服務名稱出發猜答案，只適合需求尚未出現時做初步探索。",
          "忽略 MOST、LEAST、MINIMUM 等限制詞，會選到技術可行卻不符合題目的方案。",
          "requirements first、service second",
          "同一個網站題目分別要求最低營運成本與最低延遲時，正確答案可能完全不同。",
          "AWS Well-Architected Tool|AWS Certification"),
    topic(2, "Cloud、Region、AZ 與 Edge",
          "工作負載需要在延遲、故障隔離、法規與資料位置之間取得平衡。",
          "Region決定地理與服務邊界，AZ提供獨立故障域，edge將內容或入口靠近使用者。",
          "單一AZ部署較便宜且簡單，只適合能接受該AZ中斷的非關鍵工作。",
          "把多台EC2放在同一AZ誤認為高可用，AZ故障時仍會一起失效。",
          "place state across independent failure domains",
          "台灣使用者存取美國服務，要求低延遲且資料必須留在指定Region。",
          "AWS Regions|Availability Zones|Amazon CloudFront|AWS Global Accelerator"),
    topic(3, "Server、VM、Container 與 Serverless",
          "不同執行模型把不同程度的OS、runtime與容量責任交給供應商。",
          "依控制需求、啟動時間、工作持續時間、可攜性與營運能力選擇抽象層。",
          "EC2提供最大控制；container適合封裝既有服務；serverless適合事件驅動與變動流量。",
          "只因為serverless不用管理server就忽略timeout、concurrency、cold start與依賴限制。",
          "choose the highest abstraction that still exposes required control",
          "團隊要搬移一個長時間執行的Java服務，另有每分鐘少量圖片縮圖事件。",
          "Amazon EC2|Amazon ECS|Amazon EKS|AWS Fargate|AWS Lambda"),
    topic(4, "IP、CIDR、Subnet 與 Route 基礎",
          "網路設計必須先回答地址是否重疊、封包往哪裡走，以及回程是否存在。",
          "以不可重疊CIDR規劃地址，將subnet綁定AZ，再用route table做最長前綴匹配。",
          "用安全規則阻擋封包不能修復錯誤路由；NAT也不會自動建立所有方向的連線。",
          "只檢查source到destination的路徑，漏掉return route、DNS或stateful device。",
          "connectivity = name resolution + forward path + return path + policy",
          "兩個VPC需要互連，但都使用10.0.0.0/16，且on-premises也有重疊地址。",
          "Amazon VPC|Route tables|Subnets|CIDR"),
    topic(5, "DNS、TCP、TLS 與 HTTP",
          "應用程式名稱、連線、加密與請求語意位於不同層，故障時不能混為一談。",
          "依序驗證DNS解析、TCP可達、TLS身份與HTTP回應，每層保存自己的狀態與timeout。",
          "HTTP health check可證明應用路徑；TCP health check較便宜但只證明port接受連線。",
          "看到timeout就重試，可能放大DNS、TLS或後端過載，並造成非冪等操作重複。",
          "debug from the lowest failed boundary upward",
          "使用者看到502，有些請求DNS正常但TLS握手失敗，另一些已到ALB後端。",
          "Amazon Route 53|Elastic Load Balancing|AWS Certificate Manager"),
    topic(6, "Block、File 與 Object Storage",
          "資料需要不同的存取介面、一致性、共享方式、延遲與生命週期。",
          "Block給單機檔案系統，file提供共享目錄語意，object用key與API管理獨立物件。",
          "資料庫磁碟通常用block；共享POSIX工作流用file；大量靜態內容與備份用object。",
          "把S3掛載成一般磁碟並假設rename、locking與低延遲完全等同POSIX檔案系統。",
          "select storage by access semantics before capacity",
          "影像原檔要保存十年、Linux叢集共享模型檔、資料庫要求低延遲隨機I/O。",
          "Amazon EBS|Amazon EFS|Amazon FSx|Amazon S3"),
    topic(7, "Relational、NoSQL、Cache 與 Warehouse",
          "資料模型、查詢模式、交易需求與擴展方向共同決定資料服務。",
          "先列出access patterns與一致性，再選RDS/Aurora、DynamoDB、ElastiCache或Redshift。",
          "Polyglot persistence允許不同子問題使用不同store，但增加資料同步與營運複雜度。",
          "只依資料量選資料庫，忽略join、transaction、hot key、掃描與查詢形狀。",
          "model access patterns before choosing a database",
          "訂單需要ACID交易、session需要毫秒讀取、分析師需要掃描多年事件。",
          "Amazon RDS|Amazon Aurora|Amazon DynamoDB|Amazon ElastiCache|Amazon Redshift"),
    topic(8, "Availability、Durability、Scalability 與 Elasticity",
          "這些非功能屬性描述不同風險，不能用一個『高可用』標籤取代。",
          "Availability看服務是否可用，durability看資料是否遺失，scalability看上限，elasticity看調整速度。",
          "多副本可改善某些風險，但同步故障、錯誤刪除與軟體bug仍需要備份與隔離。",
          "以S3 durability數字推論應用availability，或以Auto Scaling取代容量測試。",
          "name the property and its measurement before selecting a mechanism",
          "服務可短暫停機但不能遺失付款資料，且促銷時流量會在五分鐘內增加十倍。",
          "Amazon S3|Amazon EC2 Auto Scaling|Elastic Load Balancing|AWS Backup"),
    topic(9, "SLA、SLO、RTO、RPO 與 Business Requirement",
          "技術團隊若沒有量化可接受中斷與資料遺失，就無法選擇合理成本的架構。",
          "SLO定義正常目標，RTO限制恢復時間，RPO限制可接受資料落後，再映射到HA與DR。",
          "更低RTO/RPO通常需要更多常駐容量、自動化、同步複寫與演練。",
          "先選active-active再問需求，容易付出高成本卻仍沒有經過驗證的恢復流程。",
          "business impact sets recovery architecture",
          "財務系統RPO為零且RTO十五分鐘；內部報表可接受一天資料與四小時停機。",
          "AWS Backup|AWS Elastic Disaster Recovery|Amazon Route 53"),
    topic(10, "Shared Responsibility 與六大 Pillars",
          "雲端供應商負責部分基礎設施，但客戶仍擁有資料、身份、設定與工作負載風險。",
          "逐服務判斷AWS管理到哪一層，再用六大pillar平衡安全、可靠、效能、成本、營運與永續。",
          "Managed service能降低操作面，卻不會替客戶決定資料分類、IAM政策與應用正確性。",
          "將『AWS負責安全』理解成不需patch guest OS、不需備份或不需限制public access。",
          "managed does not mean unmanaged responsibility",
          "EC2與Lambda都處理敏感資料，團隊要分清OS patch、runtime、code與IAM責任。",
          "AWS Well-Architected Framework|Shared Responsibility Model"),

    topic(11, "VPC 與 CIDR 規劃",
          "地址規劃會限制未來VPC互連、hybrid連線、擴展與組織合併。",
          "預留不可重疊CIDR、依環境與區域分配範圍，並用IPAM集中追蹤。",
          "小CIDR節省地址但增加後續擴張與重編址風險；大CIDR則可能浪費企業地址空間。",
          "每個團隊自行使用10.0.0.0/16，之後Transit Gateway與Direct Connect無法直接路由。",
          "address space is an architectural resource",
          "企業預計建立五十個帳號、三個Region並連回兩個資料中心。",
          "Amazon VPC|AWS VPC IP Address Manager"),
    topic(12, "Subnet、Route Table 與 Internet Gateway",
          "Public/private不是subnet名稱，而是路由與資源public address共同形成的可達性。",
          "Internet-facing資源放可達IGW的subnet；private workload只保留必要出口與內部路由。",
          "Private subnet可經NAT對外發起連線，但internet不能藉此主動建立到instance的連線。",
          "只把subnet命名private卻保留0.0.0.0/0到IGW與public IP。",
          "derive exposure from effective routes and addresses",
          "ALB必須公開，但應用與資料庫不得接受internet直接連線。",
          "Amazon VPC|Internet Gateway|Route tables"),
    topic(13, "NAT Gateway、Egress 與 VPC Endpoints",
          "Private workload仍需更新套件、呼叫AWS API或外部服務，出口路徑影響安全與成本。",
          "AWS服務優先用gateway/interface endpoint；一般IPv4 internet egress再使用每AZ NAT。",
          "集中NAT可減少gateway數量，但增加跨AZ/Transit成本、路由複雜度與共同故障面。",
          "所有S3流量繞NAT，造成不必要處理費與單一AZ依賴。",
          "keep private traffic private and local when practical",
          "數百台private EC2大量讀S3，偶爾需下載internet套件。",
          "NAT Gateway|AWS PrivateLink|VPC endpoints|Amazon S3"),
    topic(14, "Security Group 與 Network ACL",
          "網路控制需要區分資源級stateful規則與subnet級stateless邊界。",
          "Security Group作主要allow-list；NACL用於粗粒度subnet防護或明確deny需求。",
          "SG自動允許已建立連線回程；NACL必須同時允許雙向與ephemeral ports。",
          "只開啟應用port卻在NACL阻擋回程ephemeral port，造成間歇timeout。",
          "place policy at the narrowest stable boundary",
          "Web tier只接受ALB流量，資料庫只接受app SG，另需封鎖一段惡意CIDR。",
          "Security groups|Network ACLs|Amazon VPC"),
    topic(15, "VPC Peering、PrivateLink 與 Transit Gateway",
          "VPC之間可共享整個網路、特定服務或經中央路由，但三種需求不同。",
          "少量一對一網路用peering；只發布服務用PrivateLink；多VPC hub-and-spoke用TGW。",
          "Peering簡單但不transitive；TGW擴展好但需治理route domains；PrivateLink只暴露endpoint service。",
          "為了讓一個API可用而互連整個CIDR，擴大blast radius並遇到重疊地址。",
          "share the minimum required connectivity",
          "三十個consumer VPC只需呼叫中央付款API，不應彼此路由。",
          "VPC Peering|AWS PrivateLink|AWS Transit Gateway"),
    topic(16, "Route 53 Routing Policies",
          "DNS可以依健康、位置、權重與延遲選endpoint，但不代理每個request。",
          "Simple、weighted、latency、failover、geolocation與multi-value依需求選用並設定health checks。",
          "Global Accelerator提供anycast與快速網路層failover；CloudFront適合cache與HTTP edge。",
          "將低TTL視為零切換時間，忽略resolver/client cache與既有connection。",
          "routing policy must match the failure and steering signal",
          "全球API要導向低延遲Region，災難時切換，並逐步將10%流量送新版本。",
          "Amazon Route 53|Health checks"),
    topic(17, "CloudFront、Global Accelerator 與 Edge",
          "全球使用者需要降低延遲、保護origin或改善非HTTP連線路徑。",
          "可cache HTTP內容用CloudFront；需要static anycast IP或TCP/UDP加速用Global Accelerator。",
          "CloudFront Functions/Lambda@Edge可在edge改寫請求，但會增加部署與除錯面。",
          "將動態、不可cache且需固定IP的工作硬套CloudFront，或忽略cache key造成資料洩漏。",
          "move computation and copies toward users only when semantics permit",
          "遊戲使用UDP且需固定入口；網站靜態內容與API則需WAF及origin protection。",
          "Amazon CloudFront|AWS Global Accelerator|Lambda@Edge"),
    topic(18, "ALB、NLB 與 Gateway Load Balancer",
          "負載平衡器在不同層理解不同資訊，影響routing、來源IP、TLS與throughput。",
          "HTTP path/host routing用ALB；高效TCP/UDP與static IP用NLB；虛擬安全設備鏈用GWLB。",
          "NLB可把流量送ALB組合L4入口與L7routing，但增加元件與診斷層。",
          "因NLB較快就用它處理需要path routing的API，結果把邏輯推回應用程式。",
          "choose the lowest network layer that understands the required decision",
          "多租戶API依host routing，支付協定走TLS passthrough，所有流量需經防火牆。",
          "Application Load Balancer|Network Load Balancer|Gateway Load Balancer"),
    topic(19, "VPN、Direct Connect 與 Hybrid Connectivity",
          "企業需要在上雲速度、頻寬穩定、加密、成本與備援之間取捨。",
          "快速建立或backup用VPN；穩定private circuit用Direct Connect；關鍵系統建立多路徑。",
          "Direct Connect不是預設端到端加密，仍可能搭配MACsec或VPN。",
          "只有單一DX connection且沒有異地或VPN備援，把電信商故障變成單點。",
          "hybrid connectivity requires path diversity and routing policy",
          "金融系統每天傳數TB資料，要求穩定延遲、加密與兩個location容錯。",
          "AWS Site-to-Site VPN|AWS Direct Connect|Direct Connect Gateway"),
    topic(20, "Multi-VPC、Hybrid DNS 與 Network Inspection",
          "大型組織需要統一解析private names、分離route domains並檢查流量。",
          "用Route 53 Resolver endpoints/rules共享DNS，TGW route tables隔離環境，inspection VPC集中安全設備。",
          "中央inspection便於治理，但對稱路由、appliance mode、跨AZ成本與容量都需設計。",
          "轉送DNS形成loop，或forward path經firewall而return path繞過，造成stateful檢查失敗。",
          "centralize policy without centralizing every failure",
          "數百VPC需解析on-premises domain，prod/dev隔離且internet egress集中稽核。",
          "Route 53 Resolver|AWS Transit Gateway|AWS Network Firewall"),

    topic(21, "IAM Principal、Role、Policy 與 Least Privilege",
          "每個人與workload都需要可撤銷、可稽核且不依賴長期密鑰的權限。",
          "人員用federation/Identity Center，workload用role與temporary credentials，政策只允許必要action/resource/condition。",
          "IAM user仍可支援特殊legacy情境，但需強MFA、rotation與明確淘汰計畫。",
          "將AdministratorAccess當作除錯手段後永久保留，或把access key寫入程式碼。",
          "identity is the primary security perimeter",
          "開發者跨三十個帳號操作，EC2與Lambda需要存取S3與DynamoDB。",
          "AWS IAM Identity Center|IAM|AWS STS"),
    topic(22, "IAM Policy Evaluation Logic",
          "同一request可能同時受identity、resource、boundary、SCP、session與KMS policy影響。",
          "先確認implicit deny，再找applicable allow，任何explicit deny都勝出，最後檢查交集型邊界。",
          "Policy Simulator可協助，但resource context與某些service-specific policy仍需真實驗證。",
          "只看到identity allow就判斷可存取，漏掉SCP、permissions boundary或key policy deny。",
          "authorization is an intersection of independent guardrails",
          "Role允許kms:Decrypt，但KMS key policy與SCP讓request仍被拒絕。",
          "IAM policies|Service control policies|Permissions boundaries|AWS KMS"),
    topic(23, "STS、Cross-account 與 Federation",
          "跨帳號與企業身份不應靠複製user或分享長期secret。",
          "以IdP登入後assume role；trust policy決定誰可扮演，permissions policy決定扮演後能做什麼。",
          "Resource policy可直接授權某些cross-account access，適合S3/SQS等支援服務。",
          "只設定role permissions卻沒有trust，或ExternalId/condition錯誤造成confused deputy。",
          "separate who may assume from what the role may do",
          "SaaS供應商需讀客戶帳號資料，內部員工以公司目錄登入多帳號。",
          "AWS STS|IAM roles|AWS IAM Identity Center"),
    topic(24, "IAM Identity Center 與企業身份",
          "企業需要集中人員生命週期、MFA與多帳號權限，而非在每個帳號建立user。",
          "整合外部IdP，使用permission sets下發temporary role sessions並集中assignments。",
          "Directory Service適合需要managed Microsoft AD語意的workload，不等於所有console federation。",
          "離職只停用一個帳號卻遺留各AWS帳號local users與access keys。",
          "centralize workforce identity, decentralize workload roles",
          "跨國企業使用Entra ID，要求依群組存取不同OU帳號並快速撤權。",
          "AWS IAM Identity Center|AWS Directory Service"),
    topic(25, "Organizations、OU、SCP 與 Control Tower",
          "多帳號需要一致guardrails、帳號供應、log與安全基線。",
          "Organizations建立階層，SCP限制最大權限，Control Tower提供landing zone與預防/偵測controls。",
          "SCP不授權且不影響management account；過度集中OU會使例外與blast radius難管理。",
          "用SCP寫細粒度應用權限，或測試不足便在root套explicit deny。",
          "govern centrally, operate within bounded accounts",
          "公司快速建立上百個帳號，要求禁止關閉CloudTrail及限制未核准Region。",
          "AWS Organizations|AWS Control Tower|Service control policies"),
    topic(26, "Resource Policy、Boundary 與 Delegated Administration",
          "平台團隊需要讓應用團隊自行建立role，同時確保不能超過安全上限。",
          "用permissions boundary限制可委派權限；resource policy授權資源；delegated admin把服務管理移出management account。",
          "Tag/attribute-based access可減少policy數量，但標籤治理本身必須可信。",
          "允許iam:*後期待開發者自律，或把resource policy Principal寫成無條件星號。",
          "delegate capability inside non-bypassable boundaries",
          "平台允許各團隊建立deployment roles，但不得讀取其他產品資料。",
          "IAM permissions boundaries|Resource policies|AWS Organizations"),
    topic(27, "KMS、Envelope Encryption 與 Key Policy",
          "大量資料需要可擴展加密、集中key control、rotation與audit。",
          "KMS保護data key；資料由data key本地加密，key policy與grants控制誰能使用CMK。",
          "CloudHSM提供更直接的HSM控制，但營運責任與整合成本較高。",
          "只給IAM allow卻未被key policy允許，或跨Region複製資料卻未規劃keys。",
          "separate data encryption from key authorization",
          "S3、EBS與應用欄位需加密，安全團隊要求集中撤權與CloudTrail稽核。",
          "AWS KMS|AWS CloudHSM|Envelope encryption"),
    topic(28, "Secrets Manager、Parameter Store 與 ACM",
          "密碼、API key與certificate都有生命週期，不能放在AMI、環境檔或repo。",
          "需自動rotation的secret用Secrets Manager；一般設定/secure string可用Parameter Store；certificate用ACM。",
          "Runtime retrieval降低靜態洩漏但增加權限、cache、availability與quota考量。",
          "每次request同步讀secret造成延遲與throttling，或rotation後connection pool仍用舊值。",
          "credentials are dynamic dependencies, not configuration constants",
          "RDS密碼每月rotate，Lambda需無重啟切換，public ALB需自動續期TLS。",
          "AWS Secrets Manager|AWS Systems Manager Parameter Store|AWS Certificate Manager"),
    topic(29, "WAF、Shield、Firewall Manager 與 Network Firewall",
          "DDoS、L7惡意請求與網路流量檢查需要不同控制面。",
          "WAF處理HTTP規則，Shield處理DDoS保護，Network Firewall檢查VPC流量，Firewall Manager集中下發。",
          "Security Group仍負責資源級allow-list，不能由WAF取代。",
          "用NACL阻擋SQL injection，或只部署WAF卻讓origin可被直接繞過。",
          "layer controls by threat model and protocol visibility",
          "全球網站需阻擋bot與SQL injection，並讓所有帳號套用一致WAF policy。",
          "AWS WAF|AWS Shield|AWS Firewall Manager|AWS Network Firewall"),
    topic(30, "GuardDuty、Inspector、Macie、Detective 與 Security Hub",
          "組織需要區分威脅偵測、漏洞、敏感資料與調查聚合。",
          "GuardDuty找可疑活動，Inspector掃workload漏洞，Macie找S3敏感資料，Detective協助調查，Security Hub彙整。",
          "Config/Audit Manager偏合規與設定證據，CloudTrail提供API活動原始紀錄。",
          "看到Security Hub finding便誤以為它自行掃描所有資源，或沒有owner與response workflow。",
          "detection requires signal ownership and response paths",
          "安全中心要集中各帳號finding，判斷憑證外洩、EC2漏洞與S3個資。",
          "Amazon GuardDuty|Amazon Inspector|Amazon Macie|Amazon Detective|AWS Security Hub"),
    topic(31, "資料分類、備份、Retention 與 Compliance",
          "不同資料有不同機密性、保存期限、刪除義務與復原要求。",
          "先分類，再套encryption、access、lifecycle、Object Lock、Backup Vault Lock與稽核證據。",
          "Replication改善副本可用性但會複製邏輯刪除；backup提供時間點復原但需測試。",
          "只確認備份job成功，從未驗證restore、權限、KMS key與跨帳號隔離。",
          "a backup is useful only after a verified restore",
          "勒索軟體風險下，財務資料需七年WORM保存且可跨帳號恢復。",
          "AWS Backup|Amazon S3 Object Lock|AWS Artifact|AWS Audit Manager"),

    topic(32, "EC2 Instance、AMI 與 Placement",
          "EC2選型同時牽涉CPU、memory、network、accelerator、license與failure placement。",
          "以profile選instance family，AMI固化可重建映像，placement group依latency或隔離需求使用。",
          "Graviton可降低price/performance但需architecture相容；Dedicated Host適合特定license與隔離。",
          "只依vCPU數選型，忽略network/EBS bandwidth、burstable credits與單AZ容量。",
          "measure the constrained resource, then choose compute",
          "HPC需要低延遲東西向網路，商用軟體依socket授權，web tier可水平擴展。",
          "Amazon EC2|Amazon Machine Images|Placement groups"),
    topic(33, "EBS、Instance Store 與 EC2 Lifecycle",
          "運算節點需要在持久性、IOPS、throughput、成本與ephemeral特性間選磁碟。",
          "需持久block用EBS；可重建scratch/cache用instance store；snapshot提供增量備份。",
          "gp3可獨立配置IOPS/throughput；io2適合高耐久低延遲關鍵I/O。",
          "把唯一資料放instance store，或誤以為stop/start後所有本機資料必然保留。",
          "ephemeral compute requires external durable state",
          "資料庫log需穩定低延遲，transcoding scratch可在失敗後重建。",
          "Amazon EBS|EC2 instance store|EBS snapshots"),
    topic(34, "Auto Scaling 與 Scaling Metrics",
          "容量必須跟需求調整，但錯誤metric會讓系統在過載後才反應。",
          "Target tracking用與負載近似成比例的metric，scheduled/predictive處理已知週期，保留warmup。",
          "CPU不適合所有workload；queue depth per worker或requests per target可能更直接。",
          "以平均CPU掩蓋hot partition，scale-in過快移除仍處理工作的instance。",
          "scale on demand signals, protect work during transitions",
          "Worker從SQS取工作，尖峰時queue age升高但CPU只有30%。",
          "Amazon EC2 Auto Scaling|AWS Auto Scaling|Amazon CloudWatch"),
    topic(35, "ALB＋ASG 高可用 Web Tier",
          "Stateless web tier需要跨AZ分流、健康檢查、自動替換與安全deployment。",
          "ALB跨至少兩AZ，ASG維持desired capacity，application health決定target是否接流量。",
          "Sticky sessions可暫時支援legacy session，但更好的長期方案是外部session store。",
          "只用EC2 status check而忽略應用deadlock，或把session放local disk阻止替換。",
          "make instances disposable and health application-aware",
          "網站instance仍可ping但thread pool卡死，部署時不可讓使用者掉session。",
          "Application Load Balancer|Amazon EC2 Auto Scaling|Amazon ElastiCache"),
    topic(36, "Lambda Execution、Concurrency 與 Cold Start",
          "事件驅動函式需要理解執行環境重用、並行上限、重試與下游保護。",
          "函式保持stateless/idempotent，以reserved concurrency隔離，必要時provisioned concurrency降低啟動延遲。",
          "Lambda適合短任務與變動流量；長時間穩定高利用率服務可能由containers/EC2更經濟。",
          "無限制擴展把RDS connection打爆，或依賴global memory一定存在。",
          "serverless removes server management, not capacity contracts",
          "API流量突增一百倍，下游RDS最多接受兩百條connection。",
          "AWS Lambda|Lambda concurrency|Amazon RDS Proxy"),
    topic(37, "API Gateway 與 Serverless API",
          "Public API需要authentication、throttling、routing、transformation與版本管理。",
          "API Gateway作managed入口，整合Lambda或HTTP backend，使用authorizer/Cognito與usage controls。",
          "ALB也能直接整合Lambda或containers，適合較簡單、已有VPC routing的HTTP服務。",
          "只依API key做身份驗證，或timeout/retry設定使client與Lambda重複寫入。",
          "put protocol policy at a managed edge",
          "行動app API需JWT、每客戶quota、request validation與canary stage。",
          "Amazon API Gateway|Amazon Cognito|AWS Lambda"),
    topic(38, "ECS、EKS、Fargate 與 ECR",
          "Container平台要在Kubernetes生態、控制需求、團隊能力與營運負擔間選擇。",
          "偏AWS整合與簡單orchestration用ECS；需要Kubernetes API/ecosystem用EKS；不管節點用Fargate。",
          "EC2 launch type提供instance與daemon控制，但需管理capacity與patch。",
          "因履歷或流行選EKS，卻沒有cluster upgrade、network policy與observability能力。",
          "platform choice must fit the operating model",
          "團隊有十個微服務、無Kubernetes經驗，另有一套必須使用K8s operator的vendor產品。",
          "Amazon ECS|Amazon EKS|AWS Fargate|Amazon ECR"),
    topic(39, "Batch、EMR 與大型計算",
          "離線工作需要queue、scheduler、依賴、重試與可中斷容量管理。",
          "一般container batch用AWS Batch；大數據Spark/Hadoop用EMR；平行HPC可搭Spot與placement。",
          "Step Functions可協調多階段工作，但不是高吞吐資料處理引擎。",
          "將大量短工作各自啟動完整cluster，或Spot interruption沒有checkpoint。",
          "separate orchestration from execution engines",
          "每天處理TB級Spark ETL，另有百萬個獨立影片轉檔工作。",
          "AWS Batch|Amazon EMR|AWS Step Functions|EC2 Spot Instances"),
    topic(40, "Elastic Beanstalk、App Runner 與 Managed Platforms",
          "團隊想快速部署web application，但需要不同程度的VPC、runtime與deployment控制。",
          "Beanstalk管理常見EC2 stack；App Runner從source/image提供更高抽象的web service。",
          "Lightsail適合簡單小型應用；完整微服務平台則考慮ECS/EKS。",
          "使用高階平台卻需要未暴露的host控制，最後以脆弱hook繞過抽象。",
          "managed platforms trade control for delivery speed",
          "小團隊要部署標準Python web app，無意管理cluster，但需autoscaling與TLS。",
          "AWS Elastic Beanstalk|AWS App Runner|Amazon Lightsail"),
]
